### PR TITLE
Warn if invalid frequency data is detected and method to fix the data

### PR DESCRIPTION
**Pull request by FranzForstmayr**
See issue #517

### CODE REVIEW

**Comment by jhillairet** [comment]
Wouldn't that make sense to separate dropping duplicates and non-increasing frequency values? `drop_invalid `can do both of course, calling `drop_duplicates() `and `drop_non_monotonic_increasing()`. 

And instead of `check_values()` which name is rather unexplicit, I propose (like in pandas) `is_monotonic_increasing()` and `duplicated()` (which [returns the duplicate values](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html#pandas.DataFrame.duplicated)? It can be use as a test using `duplicated().any ` 

what do you think?

**Comment by FranzForstmayr** [comment]
Good Idea to go similar to pandas API!
I'll change the code in a few days.

**Comment by FranzForstmayr** [comment]
Ok, thought again about this issue. 
Splitting `drop_invalid` into `drop_duplicates` and `drop_non_monotonic_increasing` would generate a lot more code, without any gain for the user. In addition we would need two seperate Warnings, to distinguish these two cases. The methods would be needed in frequency and network classes, so I don't think it's worth to change.

However, I'm open to rename the `drop_invalid` to `drop_non_strictly_monotic_increasing` or something else. Duplicates are not possible anyway, if the function is strictly monotonic increasing.

Would this be ok for you?

**Comment by jhillairet** [comment]
> Splitting `drop_invalid` into `drop_duplicates` and `drop_non_monotonic_increasing` would generate a lot more code, without any gain for the user. In addition we would need two seperate Warnings, to distinguish these two cases. The methods would be needed in frequency and network classes, so I don't think it's worth to change.

OK, I got your point. 
 
> However, I'm open to rename the `drop_invalid` to `drop_non_strictly_monotic_increasing` or something else. Duplicates are not possible anyway, if the function is strictly monotonic increasing.

Yes, I think a more meaningful function name is preferable.  `drop_non_monotonic` is maybe sufficient to understand what the function does.

**Comment by jhillairet** [comment]
merged. Thank you.

**Pull request merged**
