### PR TITLE
make nanovna2 idn function a property

### PR DESCRIPTION
**Pull request by zarath**
idn should be a property as in the abcvna base class

### CODE REVIEW

**Comment by jhillairet** [comment]
There is currently a larger reimplementation of the instruments/vi parts, cf #744. Please have a look to it, as it will be probably the new default in future version (nanoVNA has been implemented).

**Comment by zarath** [comment]
Ok. I'll take a look.

Btw. Do you consider renaming the nanavna part more clearly to nanovna_v2 or saa2? It's a little bit misleading, as the s-a-a-2/v2 has a binary protocol, opposed to the original and more common nanovna's (and -H/-F..)

**Comment by cafeclimber** [comment]
> Ok. I'll take a look.
> 
> Btw. Do you consider renaming the nanavna part more clearly to nanovna_v2 or saa2? It's a little bit misleading, as the s-a-a-2/v2 has a binary protocol, opposed to the original and more common nanovna's (and -H/-F..)

Hi, I'm the one writing the new implementation. In the vi.vna module, everything will be grouped by manufacturer, but you make a good point about changing the name of the specific instrument class. I'll rename it to nanovna.NanoVNAV2

**Comment by cafeclimber** [comment]
Also, if you are a user of the NanoVNA v2, it would be great if you had a chance to test the new implementation! Just clone my fork, install, and try running through the various commands. I don't have one on hand so was writing a lot based on the previous implementation.

**Comment by zarath** [comment]
> Also, if you are a user of the NanoVNA v2, it would be great if you had a chance to test the new implementation! Just clone my fork, install, and try running through the various commands. I don't have one on hand so was writing a lot based on the previous implementation.

Yes, I'll check it! ... I close this PR here now!

**Comment by zarath** [comment]
@cafeclimber oh, I've just seen that the request for testing was from you.... Is there a document, which methods should be mandatory and which could be optional in each driver. I've some concerns making frequency_start, stop, and step methods propertiies. They are harder to derive. despite to "normal" methods. One can discuss if it is better and more pythonic to have set_frequency_start/get_frequency_stop. Most pythonic way in my opinion would be to have just 3 attributes (start, stop, npoints) and and a method(s) to apply that values to the instrument or calculating them from a Frequency object.

**Comment by cafeclimber** [comment]
You can build the docs in my fork and there's a page with expected names. It's still very much in active development though

**Pull request closed without merging**
