### PR TITLE
Time ns warning

### PR DESCRIPTION
**Pull request by FranzForstmayr**
Similar to #792 this PR prepares skrf to use seconds instead of nanoseconds by default.

### CODE REVIEW

**Comment by FranzForstmayr** [comment]
Hmm `time.detect_span` still returns span in nanoseconds. I'm not sure, if this function is used from anyone outside `skrf`?

**Review by jhillairet — APPROVED** [review]

**Comment by FranzForstmayr** [comment]
@jhillairet do you think we need a public `detect_span` function? Otherwise we could deprecate this public function which returns nanoseconds and use an internal `_detect_span`.
If it's need, I'll need to add a `t_unit` keyword argument.

**Comment by FranzForstmayr** [comment]
Can we get this into #800 ?

**Comment by jhillairet** [comment]
> @jhillairet do you think we need a public `detect_span` function? Otherwise we could deprecate this public function which returns nanoseconds and use an internal `_detect_span`. If it's need, I'll need to add a `t_unit` keyword argument.

I have no idea how much this function is used. 

I think raising a warning in this function saying it will return time in seconds in the future is sufficient for now, and it will be included in #800. 

Then, after, and towards v1.0, it raises the need to question the [`Frequency.t_ns`](https://scikit-rf.readthedocs.io/en/latest/api/generated/skrf.frequency.Frequency.t_ns.html) attribute itself (to keep or not), and adding adding a `unit`  param to this function.

**Comment by jhillairet** [comment]
OK.There is print left over, but this could be corrected later

**Pull request merged**
