### PR TITLE
Pass kind to interpolate method (again)

### LINKED ISSUE #1194: Interpolate method appears to return linear interpolation of network regardless of "kind" parameter
I have been using the network 'interpolation' method for over a year. When I most recently ran my code, the interpolation result appears to return a linear interpolation of the network S parameters regardless of what value is passed to the 'kind' parameter. 

Thank you for looking into this.

Erik

### PR DESCRIPTION
**Pull request by FranzForstmayr**
Closes #1194

### CODE REVIEW

**Review by jhillairet — APPROVED** [review]

**Comment by jhillairet** [comment]
Once merged, I'll create a minor release integrating this fix...

**Comment by FranzForstmayr** [comment]
Great, I think about an testcase to catch this issue, but will try to merge soon

**Comment by jhillairet** [comment]
> Great, I think about an testcase to catch this issue, but will try to merge soon

the 0th order test could be testing the difference of the resulting network created using the various interpolation methods. They should be numerically different (not testing their performance). If they are all equals, there is a problem.

**Comment by ejohnson-cfs** [comment]
Thank you. Has this been corrected?

I updated RF-scikit and reran my code, but I am not seeing any difference

**Comment by jhillairet** [comment]
The patch is now included in the version 1.4.1

Please check if you are running this version.



Le mer. 6 nov. 2024, 19:50, ejohnson-cfs ***@***.***> a
écrit :

**Comment by ejohnson-cfs** [comment]
thank you. I have confirmed that I have updated to 1.4.1. I however still am seeing that the interpolation order makes no difference. Attached is a comparision of how the function used to correctly interpolate a network with 5 data points to 21, creating a smooth interpolation. Now it only creates a linear interpolation between the 5 data points. 

correct cubic interpolation of data from 5 samples to 21
incorrect cubic interpolation of data from 5 samples to 21

**Comment by FranzForstmayr** [comment]
@ejohnson-cfs can you show your code?

I just tried this:

```python
import skrf as rf
import matplotlib.pyplot as plt

ntwk = rf.Network("skrf/tests/metas_tdr/short_10ps_10g_50g.s1p")
ntwk.plot_s_smith()

f2 = rf.Frequency(10e9,50e9, 20, unit="Hz")
print(f2.f)

ntwk2 = ntwk.interpolate(f2, kind="cubic")
ntwk2.name = "interp_cubic"
ntwk2.plot_s_smith()

ntwk3 = ntwk.interpolate(f2)
ntwk3.name = "interp_default"
ntwk3.plot_s_smith()

plt.savefig("smith.png")
```
smith

**Comment by ejohnson-cfs** [comment]
Thank you Franz

Your test looks correct. 

When I ran it again on Friday, the interpolation is now working correctly. The patch appears to be correct. I am not sure why it did not work for me last Thursday and then did on Friday. I did not update the installation.

Thank you very much for your quick support on this.

Erik

**Pull request merged**
