### PR TITLE
v0.21.0

### PR DESCRIPTION
**Pull request by jhillairet**
Preparation for the next release.

## New Features or important improvements
* Interpolation improvements by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/595
* MTRL fixes by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/601 (and #602 and #603)
* multi-parameters NetworkSet and CITI and GMDIF file import by @jhillairet in https://github.com/scikit-rf/scikit-rf/pull/585 (see #584 for more details) 
* HP8510C Drivers and VISA Bugfixes by @jjoonathan in https://github.com/scikit-rf/scikit-rf/pull/591
* Speed up Circuit class by @FranzForstmayr in https://github.com/scikit-rf/scikit-rf/pull/575
* Speed up vector fitting by @FranzForstmayr in https://github.com/scikit-rf/scikit-rf/pull/605

## Bug fixes and other improvements
* Fix/dc extrapolation array by @FranzForstmayr in https://github.com/scikit-rf/scikit-rf/pull/571
* Correct error when asking db/ma from ri file by @edumur in https://github.com/scikit-rf/scikit-rf/pull/588
* Fix coefs_8term and coefs_12term by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/589
* fix reading ISO-8859-1 encoded Touchstone file and add encoding param to Network() and Touchstone() by @jhillairet in https://github.com/scikit-rf/scikit-rf/pull/587
* Vector Fitting: Notation and other minor improvements by @Vinc0110 in https://github.com/scikit-rf/scikit-rf/pull/577
* Don't initialize z0 from str by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/598
* Don't modify apply_cal input network by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/602
* Remove confusing transposes by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/603

## Documentation
* Vector Fitting: Example notebooks and docstrings by @Vinc0110 in https://github.com/scikit-rf/scikit-rf/pull/567
* Documentation fixes by @jhillairet in https://github.com/scikit-rf/scikit-rf/pull/576
* Change syntax of the images from Markdown to HTML in the de-embedding tutorial by @keikawa in https://github.com/scikit-rf/scikit-rf/pull/580
* Add citation to the IEEE journal article by @temmeand in https://github.com/scikit-rf/scikit-rf/pull/581
* Fix citation formatting that was a run-on line by @temmeand in https://github.com/scikit-rf/scikit-rf/pull/582
* DOI hyperlink and minor fixes in docs by @Vinc0110 in https://github.com/scikit-rf/scikit-rf/pull/583
* Doc corrections & example snippets by @Vinc0110 in https://github.com/scikit-rf/scikit-rf/pull/599

## CI
* Separate the test of the notebooks from the test of the code  by @jhillairet in https://github.com/scikit-rf/scikit-rf/pull/578
* Try to fix coverall stats by @FranzForstmayr in https://github.com/scikit-rf/scikit-rf/pull/568

## New Contributors
* @jjoonathan made their first contribution in https://github.com/scikit-rf/scikit-rf/pull/591

### CODE REVIEW

**Comment by denzchoe** [comment]
Thanks for the new release!
Any idea when the release will be updated in conda-forge?

```
scikit-rf                       0.18    pyh6c4a22f_0  conda-forge
scikit-rf                     0.18.1    pyhd3eb1b0_0  pkgs/main
scikit-rf                     0.18.1    pyhd8ed1ab_0  conda-forge
scikit-rf                     0.19.0    pyhd8ed1ab_0  conda-forge
scikit-rf                     0.20.0    pyhd8ed1ab_0  conda-forge
```

**Comment by jhillairet** [comment]
Today! It takes a few hours before the conda package is ready.
 I'll make an announcement just after.

**Comment by denzchoe** [comment]
strange.. version 0.21.0 is not released yet. I just checked.

**Comment by jhillairet** [comment]
Indeed... PyPi is available in case.

The PR to generate the conda package has been merged, but it seems that
something in the Azure pipeline went wrong... I'll look at it next weekend.

Julien

**Comment by Ttl** [comment]
docs haven't been built for this version yet.

**Comment by jhillairet** [comment]
> docs haven't been built for this version yet.

ok, it's done now.

**Pull request merged**
