### PR TITLE
Add methods for reading/writing networks from/to JSON strings.

### PR DESCRIPTION
**Pull request by JAnderson419**
To further speed up my web-based frontend for skrf, I moved to JSON serialized representations of Network objects for caching rather than encoding/decoding touchstone objects. JSON was about 2-3x faster than the touchstone route (after pull request #269) for the test data I was using (4-port, 20001 point sweep, 5 files). 

This pull request implements the functions I wrote in the skrf.io submodule, as well as provides a shorthand method for Network objects (to_json_string). Passes unit test.

Writing this test did bring up a more fundamental question about skrf in my mind, however. Why is it that __eq__ for networks only looks at the s parameter matrix? An early version of my encoder test compared network objects, but then failed when I added a comparison of frequency objects in because I wasn't handling the funit property correctly. I would propose that __eq__ should compare both f and s for a Network. While the /objects/ may still not be equal in all their properties, this would at least ensure that the measured objects were numerically equivalent. Alternatively, if you wanted more thorough equality for the object, you could check additional parameters such as name and have a separate function for numerically comparing s parameter measurements (with some tolerance for experimental variation) -> ex) two devices represented by Ntwk1 and Ntwk2 are the same because their S parameters are within 5% (user-defined) of each other over the measured range.

### CODE REVIEW

**Comment by helgrind** [comment]
Technically, for the measured objects to be equivalent, as you say, the measurement port impedance (characteristic impedance matrix) should also be equal!

**Comment by arsenovic** [comment]
i like it. 
is there reason why this is failing for 2.7?

**Comment by JAnderson419** [comment]
It looks like when Network.py runs 

`from io import TextIOWrapper`

Python 2.7 is trying to import TextIOWrapper from the skrf.io module whereas python 3.x imports the function from the standard library as intended. I have not used Python 2 at all, so I am not too familiar with the intricacies of how it handles imports compared to 3.x, but searching for an answer to the solution, most people say to either rename the module to not mask the standard library or to alter sys.path so that it doesn't go for relative imports first. Neither sound particularly attractive, so I am open to other suggestions from anyone more familiar with 2.7.

**Comment by JAnderson419** [comment]
Travis CI was giving me problems with xvfb. Initially it was passing on my local repo and failing to start on the scikit-rf branch. It looks like the scikit-rf build was happening on xenial (16.04) which is the new Travis CI default and uses a different syntax for xvfb. My local repo was still building on trusty (14.04), which passed with the old syntax and failed with the new syntax. I added an explicit dist statement to the .travis.yml to ensure that it builds on xenial so that the x11 testing works.

**Comment by JAnderson419** [comment]
> It looks like when Network.py runs
> 
> `from io import TextIOWrapper`
> 
> Python 2.7 is trying to import TextIOWrapper from the skrf.io module whereas python 3.x imports the function from the standard library as intended. I have not used Python 2 at all, so I am not too familiar with the intricacies of how it handles imports compared to 3.x, but searching for an answer to the solution, most people say to either rename the module to not mask the standard library or to alter sys.path so that it doesn't go for relative imports first. Neither sound particularly attractive, so I am open to other suggestions from anyone more familiar with 2.7.

fyi, this was giving me problems on 3.x as well today. It may have worked locally when I was troubleshooting #280 because I was running python from a different directory and had already imported the standard library io before I created a network. Not sure why it passed in CI if this is the case however...

**Comment by arsenovic** [comment]
ci is hard.  the xvfb is left over from plotting stuff which vince fixed. i think.

**Pull request merged**
