### PR TITLE
Change all occurences of npy to np

### PR DESCRIPTION
**Pull request by cafeclimber**
Per the discussion in #1040 , convert all instances of npy to np

### CODE REVIEW

**Review by jhillairet — APPROVED** [review]
Right, good idea, thanks. 

The py12 linter fails for some reason (?), but to me the PR ok.

**Comment by cafeclimber** [comment]
Yeah I'm not sure. All the tests pass so hm...

**Comment by FranzForstmayr** [comment]
ruff reports some errors when executing locally, that's why the test fails. However it's confusing that the errors are not shown properly. I'll check in the next few days locally.

**Comment by cafeclimber** [comment]
Seems like those changes addressed the linting issues! (Just waiting for the rtd task to finish)

**Pull request merged**
