### PR TITLE
H parameters added

### PR DESCRIPTION
**Pull request by whipstein**
Added support for hybrid parameters.

Hopefully this one should be correct.

### CODE REVIEW

**Comment by arsenovic** [comment]
whipstein, could you fix this or send me just the part you added?

**Comment by whipstein** [comment]
I'm not quite sure why it is failing the build. I'm not adding any new calls that don't already exist in other functions. Here's the code I added. Although, I did realize I forgot to re-add the Network object property and setter.

This is the Network class property and setter:
 ```       
    @property
    def h(self):
        """
        Hybrid parameter matrix.

        The h-matrix [#]_ is a 3-dimensional :class:`numpy.ndarray` which has shape
        `fxnxn`, where `f` is frequency axis and `n` is number of ports.
        Note that indexing starts at 0, so h11 can be accessed by
        taking the slice `h[:,0,0]`.


        Returns
        ---------
        h : complex :class:`numpy.ndarray` of shape `fxnxn`
                the hybrid parameter matrix.

        See Also
        ------------
        s
        y
        z
        t
        a
        h

        References
        ------------
        .. [#] http://en.wikipedia.org/wiki/Two-port_network#Hybrid_parameters_(h-parameters)
        """
        return s2h(self._s, self.z0)

    @h.setter
    def h(self, value):
        self._s = h2s(value, self.z0)
```

This is the general functions for parameter conversion.

```
def h2z(h):
    '''
    Converts hybrid parameters to z parameters [#]_ .
    Parameters
    -----------
    h : :class:`numpy.ndarray` (shape fx2x2)
        hybrid parameter matrix
    Returns
    -------
    z : numpy.ndarray
        impedance parameters
    See Also
    ---------
    inv : calculates inverse s-parameters
    s2z
    s2y
    s2t
    z2s
    z2y
    z2t
    y2s
    y2z
    y2z
    t2s
    t2z
    t2y
    Network.s
    Network.y
    Network.z
    Network.t
    References
    -----------
    .. [#] https://en.wikipedia.org/wiki/Two-port_network
    '''

    return z2h(h)


def h2s(h, z0=50):
    '''
    convert hybrid parameters to s parameters
    Parameters
    ------------
    h : complex array-like
        hybrid parameters
    z0 : complex array-like or number
        port impedances
    Returns
    ---------
    s : complex array-like
        scattering parameters
    '''

    return z2s(h2z(h), z0)


def s2h(s, z0=50):
    '''
    Convert scattering parameters [1]_ to hybrid parameters
    Parameters
    ------------
    s : complex array-like
        scattering parameters
    z0 : complex array-like or number
        port impedances.
    Returns
    ---------
    h : complex array-like
        hybrid parameters
    References
    ----------
    .. [1] http://en.wikipedia.org/wiki/S-parameters
    .. [2] http://en.wikipedia.org/wiki/Two-port_network#Hybrid_parameters_(h-parameters)
    '''
    return z2h(s2z(s, z0))


def z2h(z):
    '''
    Converts impedance parameters to hybrid parameters [#]_ .
    Parameters
    -----------
    z : :class:`numpy.ndarray` (shape fx2x2)
        impedance parameter matrix
    Returns
    -------
    h : numpy.ndarray
        hybrid parameters
    See Also
    ---------
    inv : calculates inverse s-parameters
    s2z
    s2y
    s2t
    z2s
    z2y
    z2t
    y2s
    y2z
    y2z
    t2s
    t2z
    t2y
    Network.s
    Network.y
    Network.z
    Network.t
    References
    -----------
    .. [#] https://en.wikipedia.org/wiki/Two-port_network
    '''
    h = npy.array([
        [(z[:, 0, 0] * z[:, 1, 1] - z[:, 1, 0] * z[:, 0, 1]) / z[:, 1, 1],
         -z[:, 1, 0] / z[:, 1, 1]],
        [z[:, 0, 1] / z[:, 1, 1],
         1. / z[:, 1, 1]],
    ]).transpose()
    return h
```

**Comment by alexpacini** [comment]
Python 3.7 is failing the build because of an import problem. I have the same in my pull request.
It is not related to your code I think.

**Comment by arsenovic** [comment]
sweet

**Comment by arsenovic** [comment]
you might want to add a test

**Comment by JAnderson419** [comment]
I believe the failure is coming from the fact that travis.yml currently requires IPython 5.1. IPython started requiring Python 3.x in version 6.x and is on is on 7.x now, so they probably dropped support for 5.x in Python 3.7.

**Pull request merged**
