### PR TITLE
Virtual Instruments: Adding NanoVNA V2

### PR DESCRIPTION
**Pull request by Vinc0110**
This PR adds support of the NanoVNA V2 as a virtual instrument.
Device website: https://nanorfe.com/nanovna-v2.html

### CODE REVIEW

**Comment by jhillairet** [comment]
ho great !

**Comment by jhillairet** [comment]
Hi @Vinc0110. What is tha status of this PR? Do you still consider it as a draft or could it be merged and included in the next release?

**Comment by Vinc0110** [comment]
The instrument class is mostly done, but I'm still testing it and I'm also working on an example notebook. This Friday, I finally received a Mini Circuits power splitter in the mail, which I wanted to use for testing. They provide measured S-parameters that I can use for comparison. So, I should finish the testing and the example notebook soon.

**Comment by Vinc0110** [comment]
I'm not having a lot of success with the offline calibration using scikit-rf. It might very well be my own fault, but maybe I'll leave that for another time and only provide the virtual instrument without the notebook for now.

**Comment by arsenovic** [comment]
can you do a one-port calibraiton?

**Comment by Vinc0110** [comment]
One-port and two-port calibrations both work, i.e. they execute now without a problem, but I'm not very happy with the results. As I said, I might be doing it wrong and I will try some more tomorrow. It often is confusing for me to understand how skrf is expecting the data to be ordered, see second issue in #623 .

**Comment by Vinc0110** [comment]
Ok, things look much better now. I'll proceed and write an example notebook from this 4-port test. Then this PR will soon be finished.

TwoPortOnePath

**Comment by Vinc0110** [comment]
So from my side, this PR is 90% done and only needs one more pass to check everything and maybe fine a solution for notebook execution error (the instrument is missing, of course). However, I'm leaving for one week of vacation tomorrow and won't work on this during that time.
Feel free to merge or just leave it open until I'm back. It's all fine for me.

**Comment by jhillairet** [comment]
> So from my side, this PR is 90% done and only needs one more pass to check everything and maybe fine a solution for notebook execution error (the instrument is missing, of course).

A simple solution should be to make the first cell as a markdown, for the example.

**Comment by jhillairet** [comment]
> > So from my side, this PR is 90% done and only needs one more pass to check everything and maybe fine a solution for notebook execution error (the instrument is missing, of course).
> 
> A simple solution should be to make the first cell as a markdown, for the example.

I've got a `LinAlgError` when running the second python cell in the notebook (it doesn't like a matrix inverse performed in `TwoPortOnePath`.). I'll wait for merging until you will be back to look at this.

**Comment by Vinc0110** [comment]
> A simple solution should be to make the first cell as a markdown, for the example.

Good idea. I found a nice way that still has the Python code highlighting:
```
```python
CODE HERE
```

> I've got a LinAlgError when running the second python cell in the notebook (it doesn't like a matrix inverse performed in TwoPortOnePath.).

Yes. That was the error fixed in #625. It now works without a problem.

I think this PR is finished. Please merge if everything is ok.

**Review by jhillairet — APPROVED** [review]
Great work. This is a feature that will interest many (new) users. Thank you @Vinc0110

**Pull request merged**
