### PR TITLE
Python3 compatible version

### PR DESCRIPTION
**Pull request by Hash--**
Big PR... Let's see how many errors I manage to have in Travis :) 

I've merging the changed I've made few months ago, into a fresh version of scikit-rf. Many things had changed since I've made these Python3 changes. In particular in the documentation. I've maybe screwed up my merging operation in some places... Let me know how bad this PR is.

### CODE REVIEW

**Comment by Hash--** [comment]
All green :) !

Could you have a look if I messed up something ? In particular code documentation?

**Comment by arsenovic** [comment]
@Hash--  
 sorry this took so long to respond. i am not a travisCI expert, but it looks like many of the individual commits are failing. (see the little red `x`'s  in the above commit summary).  if its not too much of a pain could you re-submit this one step at a time? if you dont want to, let me know and ill try and pick it apart. 



im not sure if i am reading this correctly or not. but if you could break this up into smaller

**Comment by Hash--** [comment]
Hi,

Indeed, I've made many successive commits, which all fails except the last
one. The last one (https://travis-ci.org/scikit-rf/scikit-rf/builds/57536731)
is successfull for both Python versions.

So now I have on my own repo a working version for both Python versions.

I do not know if I can split my PR into mutliple smaller PRs. However, even
if I can do that, Travis will indicate failures for all the intermediate
PRs except the last one (at least for Python3), because it requires all the
modifications in order to get the Python3 version working correctly.


Julien




2015-04-13 15:51 GMT+02:00 alex arsenovic <notifications@github.com>:

**Comment by arsenovic** [comment]
ok i got you.  let me take a look at it  and ill get back to you.

**Pull request merged**
