### PR TITLE
Fix  __floordiv__ operator

### PR DESCRIPTION
**Pull request by JesterEE**
Previous implementation with a single inputs caused a frequency mismatch.  If only a single network was passed, the unpacking of `other` into `b` and `c` would slice the network into 2 single frequency point networks and cause the operation to fail.  This checks the input to decide how to operate (either with 1 network [removing `other` from `self`], or 2 networks removing `other[0]` and `other[1]` from opposite sides of `self`]).

### CODE REVIEW

**Comment by arsenovic** [comment]
good fix. can you correct the conflicts to the tests can be run on travis?

**Comment by JesterEE** [comment]
@arsenovic I had a really old version of `scikit-rf` in my repos before I forked today.  Github did the right thing and didn't squash my repo with the new one and I unknowingly edited a really old version of `network.py`.  I need to rebase my fork, but I'll need to look at this a little later.

**Comment by arsenovic** [comment]
yeah i hate git. if it takes too long, i can just add your fix, and you can re-clone.

**Comment by arsenovic** [comment]
looks like it is still conflicting

**Comment by JesterEE** [comment]
Give me another couple days ... I'll clean it up

**Comment by JesterEE** [comment]
Automatically closed by Github when I rebased my fork.  See #154.

**Pull request closed without merging**
