### PR TITLE
Fixing unhandled corner case in Frequency

### PR DESCRIPTION
**Pull request by jhillairet**
The following should avoid the issues #492 and #91: with `Frequency.f` properties  and `Frequency.npoints` immutable, users should not be able to modify the frequency points.

The recommended workflow to change the frequency is to use the resampling/interpolating methods, and not directly manipulating the frequency properties.

### CODE REVIEW

**Comment by jhillairet** [comment]
notebook tests pass (on my fork), so it's should be OK to be merged. Waiting some days for additional comments if any.

**Comment by FranzForstmayr** [comment]
Should we deprecate this "feature" first and removing the functionality one release later?

**Comment by jhillairet** [comment]
Eventually. While this is more a bad practice than a feature, it's true
that some code previously written may stop working...

Le lun. 13 juin 2022 12:56, FranzForstmayr ***@***.***> a
écrit :

**Comment by jhillairet** [comment]
I'll made another PR to make a warning

**Pull request merged**
