### PR TITLE
Fixes ModuleNotFound error in docs

### PR DESCRIPTION
**Pull request by JAnderson419**
skrf install in RTD environment was broken in #494. This edits the rtd yml file to reintroduce the installation of skrf and fix that oversight.

### CODE REVIEW

**Comment by jhillairet** [comment]
> 
> 
> skrf install in RTD environment was broken in #494. This edits the rtd yml file to reintroduce the installation of skrf and fix that oversight.

What error did you see? [I've compiled the documentation yesterday](https://readthedocs.org/projects/scikit-rf/builds/14306784/) and it worked.

**Comment by JAnderson419** [comment]
I missed this as well because it looked like the docs build succeeded, but if you look in the ipynb you will see the below error. I added "pip install ." for the repo so that it installed skrf as well as the requirements, such that it can be imported during doc build. It would be good to have the doc build fail if an error is thrown during notebook execution. Perhaps this could be done through further updates to the rtd yml?

image

**Comment by jhillairet** [comment]
> I missed this as well because it looked like the docs build succeeded, but if you look in the ipynb you will see the below error. 

ho damn, I missed it (again) too. I found that the build process was quicker than usual, but didn't investigate ;)

> It would be good to have the doc build fail if an error is thrown during notebook execution.

It's possible, I can turn the parameter `nbsphinx_allow_errors` to `False`in: 

https://github.com/scikit-rf/scikit-rf/blob/f9e36e24cdcef5a01ac35a18c6f6474ba0e36c00/doc/source/conf.py#L62

but then it will fail for sure due to notebooks using `pyvisa`

**Comment by jhillairet** [comment]
it's ok now, i've rebuilt the doc

**Pull request merged**
