### PR TITLE
Add NetworkSet.write_mdif() method to export NetworkSet to a generalized MDIF file

### PR DESCRIPTION
**Pull request by jrmagers**
Also created an example:

`scikit-rf/doc/source/examples/networksets/Export Network Set as MDIF File.ipynb`

### CODE REVIEW

**Comment by jrmagers** [comment]
Is there a better location for `__optionstring()`?

**Comment by arsenovic** [comment]
great addition!  maybe the code formating can be split out somehow, or maybe it doesnt matter.
 julien what do you think ?

**Comment by jhillairet** [comment]
> great addition! maybe the code formating can be split out somehow, or maybe it doesnt matter. julien what do you think ?

Well, it is possible, that would be easier to review.

**Comment by jrmagers** [comment]
I will turn off black and resubmit the changes today.

**Comment by jhillairet** [comment]
oups sorry @jrmagers, I wished to push to my repo, but I pushed to yours instead, didn't know I could do that... 

What I did is that I:
- moved the writing logic into io.Mdif
- added test writing/rereading MDIF files
- auto guess the data type
- values and data_types as optional arguments
- add the .params_values and .params_types convenient properties to NetworkSet

**Comment by jhillairet** [comment]
- renamed `Mdif.from_networkset` to `Mdif.write` (more meaningful I think)
- add timeout on notebook
- fix npy/np 
- fix swapping S21 and S12 when necessary. Yeah, fun fact, MDIF files can also swap those two!

**Pull request merged**
