### PR TITLE
multi-parameters NetworkSet

### PR DESCRIPTION
**Pull request by jhillairet**
Requirements as described in #584

# Status 
- [x] add `params` in Network
- [x] deduce `.dims` and `.coords` NetworkSet properties
- [x] sub-NetworkSet selection from a given parameter values: `ns.sel({'a': 1})` return a len(2) NetworkSet
- [x] sub-NetworkSet selection from a given range of parameter values
- [x] sub-NetworkSet selection from a dictionnary 
- [x] Interpolation from parameter 
- [x] from MDIF
- [x] <strike> from MDL </strike>
- [x] from CITI
- [x] Documentation

### CODE REVIEW

**Comment by FranzForstmayr** [comment]
At the moment all the dims are stored inside the NetworkSet. Wouldn't it be better to use a 'params' dictionary property in each Network and create the dims in the NetworkSet dynamically? NetworkSet holds it's Networks in a simple list, and is able to query by parameter.

**Comment by jhillairet** [comment]
will continue in January... have good holidays!

**Comment by jhillairet** [comment]
As I didn't received any MDIF or etc kind of file. So I may merge as it is, and we will see later for the support of these files.

**Comment by arsenovic** [comment]
julien i dont have any mdif files but i found some here. 
https://github.com/hftools/hftools/tree/master/hftools/file_formats/tests/testdata/mdif

i had forgotten about this package, but i also noticed that hftools has some great file-format support here, https://github.com/hftools/hftools/tree/master/hftools/file_formats

maybe some of this can be re-used ?

**Comment by jhillairet** [comment]
> maybe some of this can be re-used ?

I have looked to it, but the implementation is rather obfuscated by many intermediate Objects, and I wasn't able to run it locally properly. But I'll have a look at the file examples.

**Comment by jhillairet** [comment]
>  But I'll have a look at the file examples.

Woah, some files are formatted very differently with very unconventional headers...

**Comment by jhillairet** [comment]
Here is a working version. Only miss the documentation yet.

**Pull request merged**
