### PR TITLE
Fix the issue in parse csv frequency.

### PR DESCRIPTION
**Pull request by Asachoo**
Fixes https://github.com/scikit-rf/scikit-rf/issues/1177

Added `f_unit` parsing in the `read_pna_csv()` method. This parsed `f_unit` is subsequently utilized within other functions to construct the `Network` using the **raw** `frequency array` and `f_unit` itself.

Here are test cases:
```bash
➜  scikit-rf git:(FixIssue) ✗ cat fix_issue.py   
import skrf as rf

switch_terms_csv = rf.read_all_csv('switch_terms')

for ntwk in switch_terms_csv.items():
    print(ntwk)

➜  scikit-rf git:(FixIssue) ✗ python fix_issue.py
('forward_GHz', 2-Port Network: 'forward_GHz',  300000.0-18000000000.0 GHz, 1001 pts, z0=[50.+0.j 50.+0.j])
('forward_MHz', 2-Port Network: 'forward_MHz',  300000.0-18000000000.0 MHz, 1001 pts, z0=[50.+0.j 50.+0.j])
('forward_Hz', 2-Port Network: 'forward_Hz',  300000.0-18000000000.0 Hz, 1001 pts, z0=[50.+0.j 50.+0.j])
```
[switch_terms.zip](https://github.com/user-attachments/files/17565438/switch_terms.zip)

### CODE REVIEW

**Comment by jhillairet** [comment]
> I'm wondering if we should consider refactoring the `read_all_csv()` function to utilize by `AgilentCSV` class's method instead. Or making `read_all_csv()` a `@classmethod` of `AgilentCSV`. This way, we can streamline our codebase with a more consistent approach, we can avoid patching the deprecated `read_pna_csv()` method and ensure that our CSV handling is consist.

For sure, if it works in all cases, it looks fine to me.

**Comment by Asachoo** [comment]
> > I'm wondering if we should consider refactoring the `read_all_csv()` function to utilize by `AgilentCSV` class's method instead. Or making `read_all_csv()` a `@classmethod` of `AgilentCSV`. This way, we can streamline our codebase with a more consistent approach, we can avoid patching the deprecated `read_pna_csv()` method and ensure that our CSV handling is consist.
> 
> For sure, if it works in all cases, it looks fine to me.

Ok, I will try to refactor in the next PR. This PR is still for the purpose of fixing issues.

**Review by FranzForstmayr — CHANGES_REQUESTED** [review]
As stated in the code I would suggest to just modify the data directly after reading, so that the first column is always returned in "Hz" regardless of the header, so we don't need to pass the `f_unit` through all the functions.

In general, this code is deprecated since ages, we could plan to drop this one finally, maybe with scikit-rf 2.0. If the code is still needed, we should remove the deprecation or build an appropriate alternative.

**Comment by FranzForstmayr** [comment]
@Asachoo sorry for the late review :)

**Comment by Asachoo** [comment]
Transitioned to utilizing a frequency multiplier to automatically adjust frequencies to the Hertz.

**Review by FranzForstmayr — APPROVED** [review]

**Review by jhillairet — APPROVED** [review]
Clean. Thank you.

**Pull request merged**
