### PR TITLE
Fix compatibility with python 3.10

### PR DESCRIPTION
**Pull request by jjoonathan**
Cherrypicking this into a separate, clean PR

### CODE REVIEW

**Comment by jjoonathan** [comment]
Python 3.10 removes the collections.Iterable alias to collections.abc.Iterable. This patch switches from the alias, which is no longer present in 3.10, to the full path, which does work in 3.10.

**Review by Vinc0110 — APPROVED** [review]
Looks good. Thanks for splitting the PR!

**Comment by jhillairet** [comment]
`Iterable` is also used in networkSet.py, so it may be affected as well ?

**Comment by jjoonathan** [comment]
I think the one in networkSet.py is ok because it already imports from abc, it doesn't use the alias that went away. While I was grepping around I did find another use of the alias, though. Here's the patch.

**Pull request merged**
