### PR TITLE
Modified `connect` to allow networks with frequency subsets

### PR DESCRIPTION
**Pull request by alexpacini**
With reference to #297, this allows to use networks with frequency subsets for functions that use `connect`, including calibration objects.

---
Example of usage:
```python
import skrf as rf
import numpy as np
ntwkA = rf.Network()
ntwkA.frequency.f= [1,2,3,4,5]
ntwkA.s = np.repeat(np.array([[0.9, 0.1], [0.1, 0.9]])[np.newaxis, :], 5, 0)

ntwkB = rf.Network()
ntwkB = ntwkA[2:3]
ntwkC = ntwkA**ntwkB

print(ntwkA)
print(ntwkB)
print(ntwkC)
```

    matplotlib not found while setting up plotting
    Using a frequency subset:
    3e-09-3e-09 GHz, 1 pts
    2-Port Network: '',  1e-09-5e-09 GHz, 5 pts, z0=[50.+0.j 50.+0.j]
    2-Port Network: '',  3e-09-3e-09 GHz, 1 pts, z0=[50.+0.j 50.+0.j]
    2-Port Network: '',  3e-09-3e-09 GHz, 1 pts, z0=[50.+0.j 50.+0.j]

```python
ntwkB = ntwkA[2:4]
ntwkC = ntwkA**ntwkB

print(ntwkA)
print(ntwkB)
print(ntwkC)
```

    Using a frequency subset:
    3e-09-4e-09 GHz, 2 pts
    2-Port Network: '',  1e-09-5e-09 GHz, 5 pts, z0=[50.+0.j 50.+0.j]
    2-Port Network: '',  3e-09-4e-09 GHz, 2 pts, z0=[50.+0.j 50.+0.j]
    2-Port Network: '',  3e-09-4e-09 GHz, 2 pts, z0=[50.+0.j 50.+0.j]

[Calibration files](https://github.com/scikit-rf/scikit-rf/files/3853461/mytest.zip)
```python
ideal = rf.load_all_touchstones('mytest/calkit')
cal_meas = rf.load_all_touchstones('mytest/calibration_full_freq')
cal = rf.calibration.OnePort(cal_meas, ideal, sloppy_input=True)
```

    Warning: Frequency information doesn't match on ideals[0], attempting to interpolate the ideal[0] Network ..
    Success
    Warning: Frequency information doesn't match on ideals[1], attempting to interpolate the ideal[1] Network ..
    Success
    Warning: Frequency information doesn't match on ideals[2], attempting to interpolate the ideal[2] Network ..
    Success

```python
s11 = 0.5 / 1
network = rf.Network()
network.frequency.f = [200195.3125]
network.s = [s11]
network = cal.apply_cal(network)
```

    Using a frequency subset:
    200195.3125-200195.3125 Hz, 1 pts

    /home/alex/git/github-personal/scikit-rf/skrf/calibration/calibration.py:1062: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
    To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
      abcTmp, residualsTmp = npy.linalg.lstsq(Q,m)[0:2]

### CODE REVIEW

**Comment by alexpacini** [comment]
The CI is failing but for some unmet dependencies on python 3.7, I don't think they depend on this change

**Comment by alexpacini** [comment]
With the following code the code, where one of the array is not fully contained in the other, the slice that used the interpolation was crashing, therefore I am using the slice of all the network properties
```python
import skrf as rf
import numpy as np
ntwkA = rf.Network()
ntwkA.frequency.f= [1,2,3,4,5]
ntwkA.s = np.repeat(np.array([[0.9, 0.1], [0.1, 0.9]])[np.newaxis, :], 5, 0)

ntwkB = rf.Network()
ntwkB.frequency.f= [5, 6]
ntwkB.s = [[0.9, 0.1], [0.1, 0.9]]
ntwkC = ntwkA**ntwkB

print(ntwkA)
print(ntwkB)
print(ntwkC)
```

**Comment by arsenovic** [comment]
so these types of rules are generally considered array broadcasting. https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

 however,  when too much is done automatically it becomes harder to see whats going on, harder to diagnose bugs, and easier to produce bugs. what do you think about some thing like 

    ntwkAsub = ntwkA.overlap(ntwkB)
    ntwkAsub**networkB

and i think the existing interpolate function may work for this, but an  overlap() would be nice if it explicitly failed if it needed to actually interpolate.

**Comment by alexpacini** [comment]
Yes, it is automatic broadcasting.
Can you elaborate more your suggestion?
How can it apply to the calibration, for example when one of the network objects is created on the fly and the frequency can change (and the calibration files covers all the possible changes)?

**Comment by alexpacini** [comment]
Anyway, I think both `overlap` and the network slice use the `interpolate` function.
The drawback (aside some overhead) is that trying to slice a 1 frequency network to get the single frequency will fail the interpolation. It might be worth changing the `__getitem__` to avoid interpolating when slicing directly using element indexes and to interpolate when using ranges in Hz.
This should also reduce the overhead and be friendlier when skrf is used in automatic measurements (as in control methods). I can try to implement it.

**Comment by alexpacini** [comment]
So, I squashed some commits to remove some multiple commits.

This squashed commit introduces:
- Modified `connect` to allow networks with frequency subsets
- Changed the `__getitem__` to avoid interpolation with explicit frequency indices.
- Updated the `__getitem__` to allow slicing using Frequency objects.

Avoiding the use of interpolation avoids a certain number of errors that I was getting while slicing networks with a single element.

With the modified `__getitem__`` that avoids Interpolation when the slices uses directly indices, the slice of the subset frequencies works even with one element. In the following example I am using partially overlapping subsets.

```python
%reset -f
import skrf as rf
import numpy as np

ntwkA = rf.Network()
ntwkA.frequency.f= [1,2,3,4,5]
ntwkA.s = np.repeat(np.array([[0.9, 0.1], [0.1, 0.9]])[np.newaxis, :], 5, 0)

ntwkB = rf.Network()
ntwkB.frequency.f= [5, 6]
ntwkB.s = np.repeat(np.array([[0.9, 0.1], [0.1, 0.9]])[np.newaxis, :], 3, 0)
ntwkC = ntwkA**ntwkB

print(ntwkA)
print(ntwkB)
print(ntwkC)
```

    Using a frequency subset:
    5e-09-5e-09 GHz, 1 pts
    2-Port Network: '',  1e-09-5e-09 GHz, 5 pts, z0=[50.+0.j 50.+0.j]
    2-Port Network: '',  5e-09-6e-09 GHz, 2 pts, z0=[50.+0.j 50.+0.j]
    2-Port Network: '',  5e-09-5e-09 GHz, 1 pts, z0=[50.+0.j 50.+0.j]

Just to show the additional slicing option:
```python
a = rf.Frequency(unit='Hz')
a.f = [3, 4]
print(ntwkA[a])
```

    2-Port Network: '',  3.0-4.0 Hz, 2 pts, z0=[50.+0.j 50.+0.j]

Which might be convenient in some cases.

This still works well with calibrations, which use the connect function.

**Comment by alexpacini** [comment]
Any additional comments on this?

We have been using those changes in our development platform since a week and we haven't seen anything problematic so far (but we are not using every available function).

**Comment by alexpacini** [comment]
I rebased on master to fix the CI issue.

**Comment by alexpacini** [comment]
Merged master (I preferred a merge instead of a rebase to keep track) into this pull request (to update to 0.15 I think).

**Comment by alexpacini** [comment]
I am cleaning up my branches to have a better structure in my repo. I will move this pull request to a new one using a different branch on my repo. I will make a new pull request.

**Pull request closed without merging**
