### PR TITLE
Improve tutorial for virtual instruments

### PR DESCRIPTION
**Pull request by mxxmxn**
I added documentation for the NanoVNA V2 to the tutorial.
I also replaced code boxes in Markdown cells with normal code cells. An option in the metadata of the notebook prevents the code from being executed when compiling the documentation.

### CODE REVIEW

**Comment by mxxmxn** [comment]
It looks like the code cells are still being executed during testing. Is there a way to prevent this?

**Comment by mxxmxn** [comment]
Should be fixed now

**Review by jhillairet — APPROVED** [review]
OK. Would it worth adding how to connect via TCP/IP (which has been removed) ?

**Comment by mxxmxn** [comment]
The connection to the PNA via TCP/IP is still in the documentation, but the lines are not correctly matched in the diff. The NanoVNA does not support TCP/IP.

**Comment by mxxmxn** [comment]
I just added another commit that fixes errors when compiling the documentation due to missing functions.

**Review by jhillairet — APPROVED** [review]

**Comment by jhillairet** [comment]
Thank you @mxxmxn .

**Pull request merged**
