### PR TITLE
docs changes, Network(fid) fix, and some stringio half-ways

### PR DESCRIPTION
**Pull request by arsenovic**

### CODE REVIEW

**Comment by jhillairet** [comment]
@arsenovic what is the status of this PR ? Travis failed because of Python2.7, so I think it's ok to merge isn't it?

**Comment by arsenovic** [comment]
yep ill merge it. good call on notice it colides with #433.

**Comment by luar123** [comment]
This commit reverts the last commits from pull request #428. I guess this was not intended, could you please fix it?

**Comment by jhillairet** [comment]
ho really? Damned.

**Comment by jhillairet** [comment]
> 
> 
> This commit reverts the last commits from pull request #428. I guess this was not intended, could you please fix it?

fixed in #441

**Pull request merged**
