### PR TITLE
Documentation example on network set interpolation

### PR DESCRIPTION
**Pull request by jhillairet**
Added a example in the documentation on the use of the network set in…terpolation. Added also figure and set of scattering parameters.

### CODE REVIEW

**Comment by arsenovic** [comment]
looks nice, thanks

**Comment by jhillairet** [comment]
Thanks. 

Is there something to do to update the documentation website to integrate this notebook?

**Comment by arsenovic** [comment]
it should happen automatically,  not sure why it didnt, i just triggered it .

**Comment by jhillairet** [comment]
Thanks. There are errors due to the fact it's a Python 2 engine (or old Python 3?). I can update the string handling accordingly.

**Comment by arsenovic** [comment]
yeah i hate that .  i think the notebook should be python3 compatable, and the kernel should not be specified in the notebook.

**Pull request merged**
