### PR TITLE
114 run notebooks in tests

### LINKED ISSUE #114: include notebook docs in coverage stats
would be  nice to  execute all the doc notebooks during a test suite execution to increase  our coverage.

### PR DESCRIPTION
**Pull request by ema00**
Closes #114 

Notebook tests are included using nbsmoke, but do not count for coverage.

### CODE REVIEW

**Comment by jhillairet** [comment]
Thank you. The tests are then of course failing because of the following problems in the examples & tutorials, but this is another story.
```
=========================== short test summary info ============================
FAILED doc/source/examples/circuit/Lumped Element Circuits.ipynb::/home/runner/work/scikit-rf/scikit-rf/doc/source/examples/circuit/Lumped Element Circuits.ipynb
FAILED doc/source/examples/circuit/Voltages and Currents in Circuits.ipynb::/home/runner/work/scikit-rf/scikit-rf/doc/source/examples/circuit/Voltages and Currents in Circuits.ipynb
FAILED doc/source/examples/circuit/Wilkinson Power Splitter.ipynb::/home/runner/work/scikit-rf/scikit-rf/doc/source/examples/circuit/Wilkinson Power Splitter.ipynb
FAILED doc/source/examples/matching/Impedance Matching.ipynb::/home/runner/work/scikit-rf/scikit-rf/doc/source/examples/matching/Impedance Matching.ipynb
FAILED doc/source/examples/metrology/Measuring a Mutiport Device with a 2-Port Network Analyzer.ipynb::/home/runner/work/scikit-rf/scikit-rf/doc/source/examples/metrology/Measuring a Mutiport Device with a 2-Port Network Analyzer.ipynb
FAILED doc/source/examples/mixedmodeanalysis/Mixed Mode Basics.ipynb::/home/runner/work/scikit-rf/scikit-rf/doc/source/examples/mixedmodeanalysis/Mixed Mode Basics.ipynb
FAILED doc/source/examples/mixedmodeanalysis/Mixed Mode S and Impedance Transformation.ipynb::/home/runner/work/scikit-rf/scikit-rf/doc/source/examples/mixedmodeanalysis/Mixed Mode S and Impedance Transformation.ipynb
FAILED doc/source/examples/networksets/Sorting Network Sets.ipynb::/home/runner/work/scikit-rf/scikit-rf/doc/source/examples/networksets/Sorting Network Sets.ipynb
FAILED doc/source/examples/networktheory/LNA Example.ipynb::/home/runner/work/scikit-rf/scikit-rf/doc/source/examples/networktheory/LNA Example.ipynb
============= 9 failed, 27 passed, 1 skipped in 250.64s (0:04:10) ==============
```

while it's a great improvement to test the notebooks, I wonder if as proposed by @arsenovic in #114 there is a way to add the content of the notebook to the code coverage.

**Comment by ema00** [comment]
I have been into the issue of coverage. I found that **nbsmoke** does not provide any options for adding coverage. Which I think makes sense, since these tests should work as acceptance tests.

An improvement, not related to coverage, is to add a few lines to the **testing.yml** file in order to avoid subsequent tests if notebook tests fail, and thus coverage stats be collected by coveralls no matter if notebooks tests succeed or not. This is accomplished by adding _if: ${{ always() }}_ to some parts in the file, like here:
https://github.com/ema00/scikit-rf/blob/114-experimental/.github/workflows/testing.yml
which returns this result after running:
https://github.com/ema00/scikit-rf/runs/1890542147?check_suite_focus=true
If you want, I can modify **testing.yml** to add that change.

**Comment by jhillairet** [comment]
> An improvement, not related to coverage, is to add a few lines to the **testing.yml** file in order to allow subsequent jobs to run if notebook tests jobs fail, and thus coverage stats can be collected by coveralls no matter if notebooks tests succeed or not. This is accomplished by adding _if: ${{ always() }}_ to some parts in the file, like here:

yes please, this is very useful indeed. It also gives the list of failing examples and tutorials failing as well, not only the examples as before.

**Comment by ema00** [comment]
> > An improvement, not related to coverage, is to add a few lines to the **testing.yml** file in order to allow subsequent jobs to run if notebook tests jobs fail, and thus coverage stats can be collected by coveralls no matter if notebooks tests succeed or not. This is accomplished by adding _if: ${{ always() }}_ to some parts in the file, like here:
> 
> yes please, this is very useful indeed. It also gives the list of failing examples and tutorials failing as well, not only the examples as before.

OK. Added in the last commit.

**Pull request merged**
