### PR TITLE
version v0.19.0

### PR DESCRIPTION
**Pull request by jhillairet**
It's time for a new version...

New Features
--------------
- Implementation of a deembedding class #480 by @vik-s
- Add VNA Keysight n9918a for usage in data_grabber.py  #482 by @wbarnha 
- Add `stdev` function, organize file, allow `read_all()` to recursively check directories #485 by @wbarnha 
- Add functionality to plot group delay for multiple files simultaneously  #489 by @wbarnha 
- two new features to the `VectorFitting` class #498 from @Vinc0110 : 
  - Evaluation of model passivity (functions `passivity_test()` and `is_passive()`)
  - Enforcement of model passivity (function `passivity_enforce()`)

Improvements
---------------
- Updated continuous integration, RTD setup and package dependencies in #494 and #501 by @Vinc0110
- Support of Python 3.9 in #507 by @jhillairet 
- Single Ended to Mixed Mode conversion now can usereference impedance different from 50 Ohms #510 by @FranzForstmayr 

Documentation
----------------
- Fix a lot of typos in the code docstring #484 and notebooks #491 by @nikosavola 
- Improve docstring for `Network.renumber` and many other things in #504 by @jhillairet 
- various documentation improvements in #490 by @jhillairet 
- wiki was deleted and its content was moved to main documentation #500 by @jhillairet 
- improve a lot of dosctring and type hints in #504, #505 and #506 by @Vinc0110 and @jhillairet 
- Example for tapered transmission line #511 by @jhillairet 

Bug Fixes
----------
- Fix bug #299 (offset in time vector) in #488 by @FranzForstmayr 
- Fix bug #467 (`is_symmetric`) in #502 by @Vinc0110

### CODE REVIEW

**Comment by Vinc0110** [comment]
If it's not too late: the passivity testing and enforcement routines from PR #498 for the vector fitting module are actually another new feature...

**Comment by jhillairet** [comment]
> 
> 
> If it's not too late: the passivity testing and enforcement routines from PR #498 for the vector fitting module are actually another new feature...

it's not, I've updated the version message above.

**Comment by Vinc0110** [comment]
Thanks!

**Comment by Vinc0110** [comment]
By the way, what is the scheme for the version numbers? It used to increment from 0.17 to 0.18. Then there was this "minor" bugfix release 0.18.1. Shouldn't this be a "real" release, i.e. 0.19?

**Comment by jhillairet** [comment]
> By the way, what is the scheme for the version numbers? It used to increment from 0.17 to 0.18. Then there was this "minor" bugfix release 0.18.1. Shouldn't this be a "real" release, i.e. 0.19?

You are right, the amount of updates is quite descent this time and could merit a new version number. 

To be honest, there is no official rule yet for deciding if it merits a new version or not ;)

**Pull request merged**
