### PR TITLE
Master

### PR DESCRIPTION
**Pull request by torgovanov**
New measurements instruments was added!

### CODE REVIEW

**Comment by arsenovic** [comment]
@torgovanov ,  thank you for submitting these., supporting R&S, is an important feature. 

couple comments, 
 first, i think we will have to re-arrange the location and name of these. 

second,  we have recently changed how the vi instruments are created, which you might consider using for these `vi`'s.  it makes for a much cleaner, and more maintainable vi.  here is a [link](http://scikit-rf.readthedocs.io/en/latest/api/vi/index.html#creating-a-driver) to the page about this.  ( unfortunately the VNA docs arent building correctly at the moment, but i will look at this). @dvincentwest  is the architect behind this new feature, and perhaps he can help you if you desire to do this.

**Comment by torgovanov** [comment]
Yes, I would like to do this.

**Comment by dvincentwest** [comment]
I will be happy to assist with this.  It will be a good case test of how successful we can be with a general approach to scpi instruments.

I took a look at your code and also at the SCPI command reference for Rhode & Schwartz which is here:
https://www.rohde-schwarz.com/webhelp/webhelp_zva_8/start.htm

I think many commands will probably follow the exact same syntax, so there is a good bet there is appreciable overlap.  The basic philosophy with the change was that:
1) I wanted to have a proper python function for each scpi command
2) I didn't want to be writing all of those functions because its laborious and writing it by hand leaves open the possibility for a lot of inconsistency.

As such, the approach is to represent the SCPI command tree in yaml syntax and let a parser translate it into python functions.  Currently the parser allows basic python type compatiblity, taking in rational variable types (i.e. you pass an int/float for freq params and it converts it to a string as necessary for the scpi).  The generated functions can also return ints/floats/strings or lists of ints/floats/strings as desired.The parser code is found here:
https://github.com/scikit-rf/scikit-rf/tree/master/skrf/vi/scpi

The parser is general and can be called in a script as here:
https://github.com/scikit-rf/scikit-rf/blob/master/skrf/vi/vna/parse_scpi.py
We can add the RS scpi yaml to this script.

Currently this is only implemented for Keysight PNAs and all the code is in the vna module:
The Keysight SCPI command tree is in the yaml file:
https://github.com/scikit-rf/scikit-rf/blob/master/skrf/vi/vna/keysight_pna_scpi.yaml
and the output from the parser is in the scpi.py file:
https://github.com/scikit-rf/scikit-rf/blob/master/skrf/vi/vna/keysight_pna_scpi.py
The higher level driver implements the abcvna prototype and imports the scpi.py file for the low-level functions and is found here:
https://github.com/scikit-rf/scikit-rf/blob/master/skrf/vi/vna/keysight_pna.py

As I've written all of this it seems rather complicated, but the goal as Alex said is to keep the vna structure clean and easy to maintain.  I am hopeful that turns out to be true.  Perhaps you can take a look at this structure and take a stab at implementing the RS driver with the new architecture.  If you have questions let me know

The only thing here that is entirely subjective is the naming.  I have tended always towards PEP8 style names and rational variable/function names.  If you think a function name or variable name doesn't make sense, let me know and we can try to come to an agreement on something better.

**Comment by arsenovic** [comment]
thanks a lot vince,  
@torgovanov  i would also be happy to discuss this over a google hangout, if it would help.

**Comment by dvincentwest** [comment]
@torgovanov, just curious if you have made any progress with this.  As it turns out I will have need to use a R&S 4-port VNA in the coming weeks, and I will be happy to contribute and test anything you've made.  I would feel to push or share what you've got as most of these features are very much use at your own risk at this stage

**Comment by torgovanov** [comment]
I have red you notice. I understand you idea about VNA drivers. I thing that such type of driver organization is much more interesting for many reasons that I have used before. I think you should cancel my previous pull request. But I had a lot of work and did not had a time to made new drivers.

**Comment by beuerle** [comment]
ZVA support, with new vi implementation: #177

**Comment by arsenovic** [comment]
@torgovanov  should we close this, due to @beuerle 's recent addition?

**Comment by torgovanov** [comment]
Dear, colleges. 
Unfortunately I have a lot of paper and administrative work with my Ph.D. 
Now I haven't time time to help you in scikit-rf project. I hope for you understanding.
The only way I can help you suggest to try this drivers on ZVA and ZNB program emulator.

It will be better if you ask to sent this program from Chris Scholz (Texas) or from Albert Gleissner (Munich) directly. If something going wrong ask me. I will try to do my best.

Chris Scholz
Chris.Scholz@rsa.rohde-schwarz.com
Central Regional Office (Systems & EMI Products)
1500 Lakeside Parkway Suite 100
Flower Mound, Texas 75028
Tel +1 469 713-5300
Fax +1 469 713-5301
http://www.rohde-schwarz.com/USA

Albert Gleissner
Albert.Gleissner@rohde-schwarz.com
Rohde & Schwarz GmbH & Co. KG
Muehldorfstrasse 15
81671 Munich
Germany
Tel +49 89 4129-0
Fax +49 89 4129-12164
http://www.rohde-schwarz.com

**Pull request closed without merging**
