### PR TITLE
Add citation to the IEEE journal article

### PR DESCRIPTION
**Pull request by temmeand**
Some of the community members wrote an IEEE Microwave Magazine article <https://ieeexplore.ieee.org/document/9632487>. This adds links and example citations.

### CODE REVIEW

**Comment by temmeand** [comment]
I can submit a PR of the same text over to the webpage repo once this is approved.

**Comment by jhillairet** [comment]
Good idea, thank you.

**Comment by jhillairet** [comment]
the documentation should be updated by 30 minutes

**Comment by Vinc0110** [comment]
Something happened with the formatting:
citation

**Comment by FranzForstmayr** [comment]
You need an ultrawide monitor ;)

**Comment by temmeand** [comment]
I noticed that too. #582 hopefully takes care of it. That is the formatting I used when for the website PR.

**Pull request merged**
