### PR TITLE
Interpolate calibration network to match input network

### PR DESCRIPTION
**Pull request by cactorium**
For https://github.com/scikit-rf/scikit-rf/issues/815 , I did some basic testing and it seems to work, would you want me to write some test cases for it?

EDIT: I guess the current test cases are doing a good job, gimme a bit

### CODE REVIEW

**Review by jhillairet — APPROVED** [review]

**Comment by Ttl** [comment]
I don't like this too much as a silent default option since interpolating raw measurements in general doesn't work. It requires that the frequency spacing is small enough that there is no aliasing in the error network. Even in the case that it is fulfilled interpolating loses accuracy since linear interpolation of S-parameters is not very accurate.

**Comment by cactorium** [comment]
Would enabling it via a keyword flag be a reasonable compromise? As in
`cal.apply_cal(meas, interpolate=True)`

And would it be better to interpolate in some different space?

**Comment by Ttl** [comment]
Here is an example demonstrating the problem with interpolation:

```python
import matplotlib.pyplot as plt
import skrf
skrf.stylely()

NPTS = 101

freq1 = skrf.F(75, 100, NPTS, unit='GHz')
freq2 = skrf.F(75, 100, 2*NPTS, unit='GHz')

wg  = skrf.RectangularWaveguide(freq1, a=100*skrf.mil, z0=50, rho='gold')
wg2 = skrf.RectangularWaveguide(freq2, a=100*skrf.mil, z0=50, rho='gold')

# Error networks
E = wg.thru()**wg.line(200, 'mm', z0=40)**wg.thru()
E2 = wg2.thru()**wg2.line(200, 'mm', z0=40)**wg2.thru()

# Calibrate using freq1 media
ideals = [
        wg.short( name='short'),
        wg.delay_short( 45.,'deg',name='ew'),
        wg.delay_short( 90.,'deg',name='qw'),
        wg.match( name='load'),
        ]
measured = [E**k for k in ideals]

cal = skrf.OnePort(
    is_reciprocal = True, 
    ideals = ideals, 
    measured = measured,
    )

# Same DUT with different frequencies
dut = E**wg.line(10, unit='mm', z0=20)**wg.resistor(50)**wg.short()
dut2 = E2**wg2.line(10, unit='mm', z0=20)**wg2.resistor(50)**wg2.short()

# Calibrate the DUT using the same cal
cal.apply_cal(dut).plot_s_db(label='Original')
cal.apply_cal(dut2).plot_s_db(label='Interpolated')
```

cal_interp

The result improves if the number of points is raised, but for some reason some artifacts remain even with high number of points.

I would prefer that user would interpolate measurements themselves if they think it's possible in their case.

**Comment by Vinc0110** [comment]
I agree with @Ttl.
For the problem with the frequency zoom described in #815, the right thing would probably be to create two separate calibrations: one for the coarse grid, another for the finer one.

**Comment by cactorium** [comment]
Huh, I guess I didn't notice that in my testing because I was looking at a Smith chart at values fairly close to the center, it looks like the interpolation doesn't work as well as I thought. No other settings seem to improve it so I guess I'll adjust the frequency settings before starting a run to coincide with the calibration grid

**Pull request closed without merging**
