### PR TITLE
v0.24.0

### LINKED ISSUE #754: Possible mistake in the 'SOLT Calibration Standards Creation' example
I have a self-built cal kit and I've been working on fitting Keysight's model to measured S-parameters, so that I can plug the coefficients into my E5062A VNA's cal kit definitions.

I've been using the code from the SOLT Calibration Standards Creation example and it's been extremely helpful (thank you @biergaizi!), but I noticed that it wasn't matching the VNA's internal model when `offset_z0` was set to anything other than 50.

In the example, when creating the mediums `z0` is set to 50:

https://github.com/scikit-rf/scikit-rf/blob/dde299c2f9e8c38f90665db6d90a22a6b6d831f1/doc/source/examples/metrology/SOLT%20Calibration%20Standards%20Creation.ipynb?short_path=ad9db82#L321-L337

However, in the summary at the end `z0` is set to `offset_z0`:

https://github.com/scikit-rf/scikit-rf/blob/dde299c2f9e8c38f90665db6d90a22a6b6d831f1/doc/source/examples/metrology/SOLT%20Calibration%20Standards%20Creation.ipynb?short_path=ad9db82#L553

I'm still getting my head around all the theory, but I *think* the latter code is a mistake and `z0` should also be set to 50 here. If I make that change, then the model matches what I see from the VNA very well.

FWIW, my test procedure looks like this: I do a least_squares fit to find suitable coefficients to match the model to my measured S-parameters, program those into the VNA, and do a response cal on that particular standard. I leave the standard connected, take a measurement, and then compare it to my stored S-params.

### PR DESCRIPTION
**Pull request by jhillairet**
The version 0.24 of scikit-rf includes a lot of improvements and bug fixes.

Note that this version officially drops the support for Python 3.6. The minimum required python version is thus now Python 3.7. 

## Improvements and new features
* Improvement of the accurary of the OpenShort and ShortOpen de-embedding by @keikawa in https://github.com/scikit-rf/scikit-rf/pull/739. 
* (Huge) Speed improvement in the `s2s` function, particularly useful when working with large matrices (>300 ports), by avoiding unecessary conversion of S-matrix definition by @qmfrf in https://github.com/scikit-rf/scikit-rf/pull/738
* Fix and Update methods in the virtual instrument module which called deprecated pyvisa methods by @cafeclimber in https://github.com/scikit-rf/scikit-rf/pull/409
* New time-domain gating implementation using time-domain multiplication instead of frequency-domain convolution. This gives a speed benefit of multiple orders of magnitude, depending on the number of samples by @Vinc0110 in https://github.com/scikit-rf/scikit-rf/pull/735
* `read_all` now sort files by default, to obtain a reproducible behaviour, by @xafra in https://github.com/scikit-rf/scikit-rf/pull/746
* Important speed improvement in `network_2_dataframe` by @stevehamblin in https://github.com/scikit-rf/scikit-rf/pull/761
* Make vector fitting Spice output compatible to LTSpice by @FranzForstmayr in https://github.com/scikit-rf/scikit-rf/pull/760
* Added a new operator `>>` for 4-port network cascading with reversed indexing ("1=>2/3=>4" instead than "1=>3/2=>4") by @capn-freako in https://github.com/scikit

## Documentation
* add a warning in the docstring to inform matlab users of the differences compared to matlab original implementation.
The differences are: i) FIX-2 is flipped (there is already a numbering diagram in docstring) and ii) Better root choice solution to avoid 180° phase jumps in certain circumstances (NZC methods only) by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/781
* Updates the documentation to highlight importance of different offset and port impedances, followed by 3 usage examples, close #754. by @biergaizi in https://github.com/scikit-rf/scikit-rf/pull/779
* Fixing typo and reference in Qfactor example by @jhillairet in https://github.com/scikit-rf/scikit-rf/pull/767-rf/scikit-rf/pull/747

## Bug Fixes
* Fix `plot_s_polar()` for matplotlib version >=3.6 (#762) by @Vinc0110 in https://github.com/scikit-rf/scikit-rf/pull/765
* Vector Fitting: bugfix for data including dc samples by @Vinc0110 in https://github.com/scikit-rf/scikit-rf/pull/768

## Code Quality Improvements and Continuous Integration
* Move requirements specification to PEP 0621 by @FranzForstmayr in https://github.com/scikit-rf/scikit-rf/pull/752
* Create codeql.yml by @FranzForstmayr in https://github.com/scikit-rf/scikit-rf/pull/772
* Treat all warnings in tests as errors by @FranzForstmayr in https://github.com/scikit-rf/scikit-rf/pull/771
* Try to fix rtd build by @FranzForstmayr in https://github.com/scikit-rf/scikit-rf/pull/775
* use pyupgrade for python3.7+ by @FranzForstmayr in https://github.com/scikit-rf/scikit-rf/pull/776

## New Contributors
* @qmfrf made their first contribution in https://github.com/scikit-rf/scikit-rf/pull/738
* @cafeclimber made their first contribution in https://github.com/scikit-rf/scikit-rf/pull/409
* @capn-freako made their first contribution in https://github.com/scikit-rf/scikit-rf/pull/747

**Full Changelog**: https://github.com/scikit-rf/scikit-rf/compare/v0.23.1...v0.24.0

### CODE REVIEW

**Comment by Vinc0110** [comment]
Please await my PR for issue #757. I'm working on it and hope to finish it this weekend.

**Comment by jhillairet** [comment]
> Please await my PR for issue #757. I'm working on it and hope to finish it this weekend.

OK

**Comment by FranzForstmayr** [comment]
We should mention, that #752 changed the minimum required python version to Python 3.7. If this is not wanted, we could change the pyproject.toml file

**Comment by jhillairet** [comment]
> We should mention, that #752 changed the minimum required python version to Python 3.7. If this is not wanted, we could change the pyproject.toml file

The official support for Python 3.6 ended 9 months ago, so I guess it is ok to start from 3.7.

I will mention it in the release/changelog message.

**Comment by biergaizi** [comment]
Please also review PR #779 for a documentation update and includes it in v0.24 if it's appropriate.

**Comment by jhillairet** [comment]
Updated the list of change for now. 

Do you think the current PR (I mean the non-draft ones) could be merged soon? (It seems the latest CI errors comes from latest versions of CI packages, tests are passing locally so I believe it is not a problem)

**Comment by mhuser** [comment]
Could we add #781 if we manage to review it?

**Comment by jhillairet** [comment]
> Could we add #781 if we manage to review it?

Sure. I think all the non-draft PRs could be merged before the next release:
image

**Comment by jhillairet** [comment]
Release message updated above, for review.

**Pull request merged**
