### PR TITLE
v1.2.0

### PR DESCRIPTION
**Pull request by jhillairet**
## What's Changed
* fix shiftNPoints in IEEEP370_SE_ZC_2xThru by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/1103
* fix frequency for npoints=1 by @mxxmxn in https://github.com/scikit-rf/scikit-rf/pull/1108
* Add MDIF functionality for improved interaction with ADS by @wsapia in https://github.com/scikit-rf/scikit-rf/pull/1104
* Drop python 3.7 to use literals and walrusses :) by @FranzForstmayr in https://github.com/scikit-rf/scikit-rf/pull/1102
* Optimize the performance of Circuit s_external mehod by @Asachoo in https://github.com/scikit-rf/scikit-rf/pull/1101
* Optimize Circuit Class Performance with Attribute Caching by @Asachoo in https://github.com/scikit-rf/scikit-rf/pull/1113
* Improve documentation for NanoVNA V2 by @mxxmxn in https://github.com/scikit-rf/scikit-rf/pull/1109
* Fixed the issue of incorrect voltage results in circuit connections. by @Asachoo in https://github.com/scikit-rf/scikit-rf/pull/1107
* Fix the network.concat_ports() issue. by @Asachoo in https://github.com/scikit-rf/scikit-rf/pull/1120
* Fixed the issue of deteriorating circuit performance with super large-scale networks (like HFSS) by @Asachoo in https://github.com/scikit-rf/scikit-rf/pull/1118
* Cal input validation by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/1121
* Adding S-parameter definition in Touchstone V1 comment by @Asachoo in https://github.com/scikit-rf/scikit-rf/pull/1117
* fix Network.connect swap the ports when connecting two 2-ports by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/1128
* Use port z0 for plot_z_time_step, plot_z_time_impulse, restore missing ylabel and add modes subscript to plot trace names for mixed-modes networks by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/1124
* Optimize the performance of loading TouchStone files. by @Asachoo in https://github.com/scikit-rf/scikit-rf/pull/1130
* Optimize interpolation performance by pre-cropping data. by @Asachoo in https://github.com/scikit-rf/scikit-rf/pull/1122
* Rational interpolation improvement. by @Asachoo in https://github.com/scikit-rf/scikit-rf/pull/1129
* Optimize Circuit Reduction Order and Increase Cycle Priority in Circuit Reduction by @Asachoo in https://github.com/scikit-rf/scikit-rf/pull/1126
* Enhance IEEEP370 deembedding documentation, plots, code readability and verbose output  by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/1114
* Fixed the Frequency issue when creating a Network using the f_unit and frequency arguments. by @Asachoo in https://github.com/scikit-rf/scikit-rf/pull/1133
* Impulse Response  by @FranzForstmayr in https://github.com/scikit-rf/scikit-rf/pull/1077
* Pass through kwargs for NetworkSet.write_mdif to use any of the arguments in Network.write_touchstone by @wsapia in https://github.com/scikit-rf/scikit-rf/pull/1135
* Add IEEE 370 Initial quality checking in frequency domain by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/1134
* IEEE 370 SE figures by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/1136

## New Contributors
* @mxxmxn made their first contribution in https://github.com/scikit-rf/scikit-rf/pull/1108
* @wsapia made their first contribution in https://github.com/scikit-rf/scikit-rf/pull/1104

**Full Changelog**: https://github.com/scikit-rf/scikit-rf/compare/v1.1.0...v1.2.0

### CODE REVIEW

**Comment by jhillairet** [comment]
Updated. I think it's time for a new version, OK?

**Comment by mhuser** [comment]
> Updated. I think it's time for a new version, OK?

Sounds good!

**Comment by jhillairet** [comment]
> Should we include #1112 as well, as this one is really a bug?

Eventually, but it's not ready yet.

**Comment by mhuser** [comment]
Hello @jhillairet 
I just did #1140 to separate IEEE 370 fixture electrical requirements and frequency domain quality metrics in separate classes. This should avoid uncontrolled growth of the IEEEP370 abstract base class with static functions.

I think it is interesting to merge this before the first time we introduce these capabilities in the released version 😄

**Comment by jhillairet** [comment]
Should we wait for #1141 @mhuser ?

**Comment by mhuser** [comment]
> Should we wait for #1141 @mhuser ?

Thank you for asking! I think we should not. It will be best to be tested in master for some time. This means the version can be released 😃

**Comment by jhillairet** [comment]
> This means the version can be released 😃

OK, the new version has been released on PyPi and soon to be on Conda. 

@mhuser , for the release message, I did follow well your work on IEEEP370. Could you make a summary?

**Comment by mhuser** [comment]
@jhillairet 
Thank you very much for the release!

> IEEE 370 de-embedding capabilities are extended with S-parameters quality checking in the time domain and fixture electrical requirements plotting. The example notebook showcases these new functionalities.
> An issue with the leadin parameter is fixed and the mixed-modes plotting syntax is simplified with automatic mode subscript labels and proper impedance handling. The class architecture was reworked to minimize code duplication, type hints, and add docstrings without a major change to the API.

**Pull request merged**
