### PR TITLE
Start touchstone 2 support

### LINKED ISSUE #400: Touchstone parser issues with Ansys touchstone 2.0 files
Hello,

There are some issues parsing Touchstone 2.0 files generated by HFSS/Network Explorer.  
An example of such file is:
[ansys_test.zip](https://github.com/scikit-rf/scikit-rf/files/5362864/ansys_test.zip)

I've noticed three problems.  One is that the parser doesn't support `[matrix format]` keyword that is used by Ansys (although it only seems to generate full matrices). 

The parser is sensitive to location of  `[number of ports]` keyword when there are HFSS port names in the comments.  The comments precede the keyword. The parser seems to check the port number before the `rank` variable is assigned. And  `rank` is not know up front because this is a .ts file.

This is a mixed port reference case where  `[reference]` spans multiple lines -- and has in-line comment -- but the parser doesn't handle this situation.

LR

### PR DESCRIPTION
**Pull request by FranzForstmayr**
This should close #400.

### CODE REVIEW

**Comment by FranzForstmayr** [comment]
The guys who invented touchstone format should write their parsers theirself....

**Comment by FranzForstmayr** [comment]
Does anyone use the `Touchstone` class itself without `Network`? Thinking about backward compatibilty...

**Comment by FranzForstmayr** [comment]
#753 should also work now.

**Comment by FranzForstmayr** [comment]
Mixed mode is not implemented yet.

**Comment by FranzForstmayr** [comment]
Should fix #354 as well now.

**Comment by FranzForstmayr** [comment]
from #354 

This file is marked as "Terminal data exported" but has only 1xN Port impedances....
https://github.com/scikit-rf/scikit-rf/blob/master/doc/source/examples/circuit/circuit_vi_Coaxial_T.s3p

This is why the notebooks are failing currently.

**Review by jhillairet — APPROVED** [review]
Amazing work, the new parser is very impressive! 

Some parts of it looks like magic to me, I'm discovering some Python syntax (like `self._parse_dict: dict[str, Callable[[str], None]] = {` etc). I wonder if you could add some comments here and there for future readers.

**Comment by FranzForstmayr** [comment]
> Amazing work, the new parser is very impressive!

> Some parts of it looks like magic to me, I'm discovering some Python syntax (like self._parse_dict: dict[str, Callable[[str], None]] = { etc). I wonder if you could add some comments here and there for future readers.

Will do of course!

@jhillairet 
Any thoughts about this file?
https://github.com/scikit-rf/scikit-rf/blob/master/doc/source/examples/circuit/circuit_vi_Coaxial_T.s3p

**Comment by jhillairet** [comment]
> @jhillairet Any thoughts about this file? https://github.com/scikit-rf/scikit-rf/blob/master/doc/source/examples/circuit/circuit_vi_Coaxial_T.s3p

Well, It's a very standard 2port solved in modal setup. Here is the same Touchstone exported with 2022.2. Any change with this one?

[circuit_vi_Coaxial_T.zip](https://github.com/scikit-rf/scikit-rf/files/13891478/circuit_vi_Coaxial_T.zip)

**Comment by FranzForstmayr** [comment]
@jhillairet does it make any difference if you disable gamma export?
https://github.com/scikit-rf/scikit-rf/issues/354#issuecomment-627930213 we can see here NxN impedances but no gamma.

**Comment by jhillairet** [comment]
> @jhillairet does it make any difference if you disable gamma export? 
Here are the different exports (also the recent "non standard Touchstone extensions for mixed reference impedances" option) 
[circuit_vi_Coaxial_T_2.zip](https://github.com/scikit-rf/scikit-rf/files/13893843/circuit_vi_Coaxial_T_2.zip)

**Review by jhillairet — APPROVED** [review]

**Pull request merged**
