### PR TITLE
Preparing for v0.23.0

### LINKED ISSUE #667: CPW Media impedance does not  account for strip thickness
When writing #665 , we observed that `Media.CPW` strip thickness `t` is not used to correct the characteristic impedance.
Currently, it only affect the conductor loss.
Qucs project provide equations and references to correct the impedance and effective permittivity to account for strip thickness.

### LINKED ISSUE #684: 180° phase jumps with IEEEP370_SE_NZC_2xThru deembedding
While using IEEEP370_SE_NZC_2xThru deembedding to extract side1 and side2 of a 100mm CPWG line measurement, 180° phase jumps appeared in insertion loss, inducing corresponding phase error in deembedding results:
image

These are caused by the computation of `e01` and `e10` using `sqrt`. The results of `sqrt` could be either positive or negative and the correct solution shall be picked.

This is done here:
https://github.com/mhuser/scikit-rf/blob/b7d026cbf513924e07c97274aab311d1e54f454f/skrf/calibration/deembedding.py#L1152-L1161
and here:
https://github.com/mhuser/scikit-rf/blob/b7d026cbf513924e07c97274aab311d1e54f454f/skrf/calibration/deembedding.py#L1163-L1172

The test assume the sign invert at each positive slope change of the phase. This is correct, but calibration error and measurement noise can cause positive spikes of small amplitudes that trigger the sign inversion wrongly, this is what happens on above plot:
image

### PR DESCRIPTION
**Pull request by jhillairet**
- version ++
- removing outdated/no more necessary files (travis, binstar)

The version 0.23 of scikit-rf includes a *lot* of improvements and bug fixes (with a huge work from @Ttl , @mhuser and @biergaizi !)

This new release also includes a new feature, the Quality factor class `Qfactor`, [which allows determining the loaded and unloaded quality factors of a Network](https://scikit-rf.readthedocs.io/en/latest/tutorials/Q-Factor.html).

The development activity of scikit-rf continues to grow! The scikit-rf development team has been consolidated with additional collaborators: @Ttl , @mhuser, @FranzForstmayr and @Vinc0110. Welcome and thank you!

# New Features
* [Q-factor(s) fitting](https://scikit-rf.readthedocs.io/en/latest/tutorials/Q-Factor.html) by @jhillairet in https://github.com/scikit-rf/scikit-rf/pull/637

# Improvements
## Network and Media
* [Add support for initializing network with different parameters](https://scikit-rf.readthedocs.io/en/latest/tutorials/Networks.html#from-z-parameters) by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/657
* More accurate Coaxial resistance model by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/649
* Z0 getter fix by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/664
* Improve s2z, z2s, s2y and y2s accuracy by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/661
* cpw warns if t < 3 * skin_depth by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/665
* Consistent Network handling with different s_def by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/655
* Refactor CPW media to fix #667 by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/676
* Fixing unhandled corner case in Frequency by @jhillairet in https://github.com/scikit-rf/scikit-rf/pull/700
* Putting back temporarely .f and .npoints setter for warning users by @jhillairet in https://github.com/scikit-rf/scikit-rf/pull/714
* warns of future deprecation of media line parameter embed by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/715

## Circuit
* Mark Circuit Ports with attribute instead of name by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/671

## Instruments
* Fixed NanoVNA backend configuration for PyVISA-py by @Vinc0110 in https://github.com/scikit-rf/scikit-rf/pull/669
* Fix compatibility with python 3.10 by @jjoonathan in https://github.com/scikit-rf/scikit-rf/pull/674
* HP8510C Sweep Plan by @jjoonathan in https://github.com/scikit-rf/scikit-rf/pull/675

## Touchstone, MDIF
* Fix `write_touchstone` with complex or non-equal z0 by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/672
* Add `NetworkSet.write_mdif()` method to export NetworkSet to a generalized MDIF file by @jrmagers in https://github.com/scikit-rf/scikit-rf/pull/680

## Calibration
* LRRM fix for unsymmetric thru, non-iterative lc fit by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/682
* IEEEP370 Flip FIX-2 and minor improvements by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/698
* Add forced_z11x to IEEEP370_SE_NZC_2xThru and correct typo by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/708

## Vector Fitting
* Vector Fitting: Some convenience updates by @Vinc0110 in https://github.com/scikit-rf/scikit-rf/pull/673
* Vector Fitting: Minor updates by @Vinc0110 in https://github.com/scikit-rf/scikit-rf/pull/706

## Documentation
* Convert All Documentation Links to Relative Path Links by @biergaizi in https://github.com/scikit-rf/scikit-rf/pull/713
* Update logos by @jhillairet in https://github.com/scikit-rf/scikit-rf/pull/716
* New example: Defining SOLT calibration standards. by @biergaizi in https://github.com/scikit-rf/scikit-rf/pull/663
* Fix SOLT cal kit example HTML rendering by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/686
* Adding the IEEEP370 deembedding methods to the docstring by @jhillairet in https://github.com/scikit-rf/scikit-rf/pull/689
* SOLT cal kit example: more formatting and typo fixes by @biergaizi in https://github.com/scikit-rf/scikit-rf/pull/690
* Minor changes in IEEE P370 doc by @jhillairet in https://github.com/scikit-rf/scikit-rf/pull/694
* New example: [Defining SOLT calibration standards](https://scikit-rf.readthedocs.io/en/latest/examples/metrology/SOLT%20Calibration%20Standards%20Creation.html). by @biergaizi in https://github.com/scikit-rf/scikit-rf/pull/663
* Documentation updates by @jhillairet in https://github.com/scikit-rf/scikit-rf/pull/709
* [Three Receivers Calibration](https://scikit-rf.readthedocs.io/en/latest/examples/metrology/Calibration%20With%20Three%20Receivers.html): Add Reference to NanoVNA by @biergaizi in https://github.com/scikit-rf/scikit-rf/pull/712
* [Three Receivers Calibration](https://scikit-rf.readthedocs.io/en/latest/examples/metrology/Calibration%20With%20Three%20Receivers.html): clarify SOLT procedures and source port. by @biergaizi in https://github.com/scikit-rf/scikit-rf/pull/711
* [Explain Isolation Calibration in SOLT calibration tutorial and example](https://scikit-rf.readthedocs.io/en/latest/examples/metrology/SOLT.html) by @biergaizi in https://github.com/scikit-rf/scikit-rf/pull/710
* Add higher number of ports examples to se2gmm by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/707

# Bug fixes
* Avoid division by zero at 0 Hz in DistributedCircuit by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/658
* Fix for #662 and other minor corrections by @Vinc0110 in https://github.com/scikit-rf/scikit-rf/pull/666
* Refactor MLine Media to follow qucs implementation by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/650
* fix #684 phase jumps in 2xthru deembedding by @mhuser in https://github.com/scikit-rf/scikit-rf/pull/687
* Remove comparison to CPW model from MTRL example by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/695
* Vector Fitting: Bug fix for #677 and #702 by @Vinc0110 in https://github.com/scikit-rf/scikit-rf/pull/678
* drop_non_monotonic_increasing fix for 2D z0 shape by @Ttl in https://github.com/scikit-rf/scikit-rf/pull/705

**Full Changelog**: https://github.com/scikit-rf/scikit-rf/compare/v0.22.1...v0.23.0

### CODE REVIEW

**Comment by mhuser** [comment]
> with a huge work from [...]

Thanks ! Seems there is a small typo with @Ttl mention in the first part of PR description 😉

**Comment by jhillairet** [comment]
> > with a huge work from [...]
> 
> Thanks ! Seems there is a small typo with @Ttl mention in the first part of PR description 😉

indeed, corrected !

**Comment by Vinc0110** [comment]
How about releasing v0.23.0 this weekend? We have quite a number of open PRs, but maybe we can merge most of them and can leave the others for the next release. There is a lot of activity - which is great - and I have a feeling the number of open PRs will never be zero again, so I suggest to just make a cut here.

**Comment by jhillairet** [comment]
I agree. I'll motivate myself to fix what I wanted to asap.

**Comment by jhillairet** [comment]
I think we are ready to release the next version. I've updated the release message above.

**Pull request merged**
