### PR TITLE
Generalized mixed mode

### PR DESCRIPTION
**Pull request by core-dd**
Tried to prepare the gmm calculations today as the changes rot on the disk here for some time now. I'm using the transformation from single ended to generalized mixed mode parameters regularly but have never tried it the other way round.

I'm considering the code as highly experimental. Unsure whether you want to add them in the current stage.

Cheers,
Jens

### CODE REVIEW

**Comment by core-dd** [comment]
the automatic calculation of z0_mm is untested at the moment :/

**Comment by arsenovic** [comment]
i dont have any way to test this, but it looks sweet! 

 you could also add some info on  this in the docs and/or examples. otherwise i dont think people will notice it.

**Comment by arsenovic** [comment]
when i have things that are untested, i try to raise a warning,  or at least mention it in the docs.

**Comment by core-dd** [comment]
a warning is mentioned in the docstrings for the se2gmm and gmm2se method, I try to find some more time to spend on the documentation this week

**Comment by arsenovic** [comment]
excellent, i think a few people have asked for this feature. you could email the scikit-rf list. getting more people to try it is good for testing!

**Comment by arsenovic** [comment]
@core-dd ,  
  what do you think about making these return a new network instead of just a s-matrix?


would that make sense?

**Comment by core-dd** [comment]
@arsenovic ,
that makes sense. Physically the network stays the same but structural seen excications etc change. Hence, nothing against that move.

**Pull request merged**
