### PR TITLE
WIP: Docs, Tutorial and Tests for De-embedding Class

### PR DESCRIPTION
**Pull request by vik-s**
Hi,

I've written up a tutorial on how de-embedding works in scikit-rf. Please let me know your comments, or let me know if something is not clear and I'll address that.

Also, I noticed that the latest release didn't have any API documentation for the de-embedding class, so I tried to make changes for that as well. I'm not entirely well versed on how sphinx builds docs, so please let me know if there are issues.

Keeping this as a WIP pull request so I can also add tests to this PR, and solicit feedback on the tutorial before requesting to merge.

thanks.

### CODE REVIEW

**Review by jhillairet — COMMENTED** [review]
It's a great tutorial, thank you!

I've sent you a PR to correct minor things in order for Sphinx to add your tutorial and create correctly the links.

Would it be possible to add a picture of a fixture in the first section of the tutorial?

**Comment by jhillairet** [comment]
Do you expect to add things to this PR?

**Comment by jhillairet** [comment]
@vik-s, Do you expect to add things to this PR?

**Comment by vik-s** [comment]
@jhillairet I wanted to add a picture like you suggested. Also wanted to put in some tests for the deembedding class.

**Comment by jhillairet** [comment]
> @jhillairet I wanted to add a picture like you suggested. Also wanted to put in some tests for the deembedding class.

OK, I wait for it then. Thank you.

**Comment by vik-s** [comment]
@jhillairet I believe I have added everything I wanted to, to this PR- so it should be ready to review. Some checks are failing here I can see, but I'm not exactly sure why.

**Comment by jhillairet** [comment]
Thank you @vik-s. I'm afraid you forgot to push `figures/onwafer_pads.png`.

> Some checks are failing here I can see, but I'm not exactly sure why.

The tests are passing. The error comes from the fact that the Coveralls service is currently down (https://status.coveralls.io/).

**Comment by vik-s** [comment]
Oops, thanks for pointing that out. I've pushed the image file now.

**Comment by jhillairet** [comment]
great, thank you. I'm OK with merging if you are good.

**Comment by vik-s** [comment]
All good to merge!

**Comment by jhillairet** [comment]
Doc is updated : online https://scikit-rf.readthedocs.io/en/latest/tutorials/Deembedding.html

**Pull request merged**
