### PR TITLE
Optimize Circuit Class Performance with Attribute Caching

### PR DESCRIPTION
**Pull request by Asachoo**
This PR optimizes the performance of the `Circuit` class by caching the `s`, `X`, and `C` attributes. This enhancement prevents unnecessary repeated calculations of `Circuit.s` during current/voltage calculations (especially when performing parametric sweeps of power and phase).

This PR improves in two aspects:
1. **Caching Attributes**
a. Cached `s`, `X`, and `C` attributes to avoid repeated calculations.
b. The `Circuit.s_external` attribute is not cached as it is a one-time operation, not frequently called externally or internally.
c. Introduced an internal variable `_connections` to store the circuit's actual connections. The circuit's cache is invalidated using a setter decorator when existing connections are modified.
3. **Type Annotations**
Implemented clearer and stricter type annotations in Circuit to improve code readability and maintenance.

Your feedback and suggestions on this PR are welcome!

### CODE REVIEW

**Comment by Asachoo** [comment]
The test case is as follows,
```python
import skrf as rf
import numpy as np
from time import time


def complex_cnxs(f_n: int):
    freq = rf.Frequency(start=1, stop=2, npoints=f_n, unit="GHz")
    line = rf.media.DefinedGammaZ0(frequency=freq, z0=50)

    snp_n = 80
    Snp = [
        rf.Network(name=f"Snp{i}", s=np.random.rand(f_n, 2, 2)) for i in range(snp_n)
    ]
    for i in range(snp_n):
        Snp[i].frequency = freq

    Gnds = [rf.Circuit.Ground(frequency=freq, name=f"Gnd{i}") for i in range(10)]
    Splitter = line.splitter(nports=4, name="Splitter")
    Splitters = [line.splitter(nports=3, name=f"Splitter_{i}") for i in range(10)]

    Input1 = rf.Circuit.Port(frequency=freq, name="Input1")
    Input2 = rf.Circuit.Port(frequency=freq, name="Input2")
    Ind = [line.inductor(name=f"Ind{i}", L=1e-9) for i in range(5)]
    Output1 = rf.Circuit.Port(frequency=freq, name="Output1")

    connections = [
        [(Snp[24], 0), (Gnds[0], 0)],
        [(Snp[5], 0), (Gnds[1], 0)],
        [(Snp[30], 0), (Gnds[2], 0)],
        [(Snp[45], 0), (Gnds[3], 0)],
        [(Ind[0], 1), (Gnds[4], 0)],
        [(Snp[15], 0), (Gnds[5], 0)],
        [(Snp[35], 0), (Gnds[6], 0)],
        [(Snp[24], 1), (Snp[25], 0)],
        [(Snp[5], 1), (Snp[6], 0)],
        [(Input1, 0), (Snp[1], 0)],
        [(Snp[12], 0), (Snp[11], 1)],
        [(Snp[12], 1), (Snp[13], 0)],
        [(Snp[30], 1), (Snp[31], 0)],
        [(Snp[20], 0), (Snp[19], 1)],
        [(Snp[33], 0), (Snp[32], 1)],
        [(Snp[33], 1), (Splitters[0], 0)],
        [(Snp[36], 1), (Splitters[0], 1)],
        [(Snp[38], 0), (Splitters[0], 2)],
        [(Input2, 0), (Snp[27], 0)],
        [(Snp[7], 0), (Snp[6], 1)],
        [(Snp[7], 1), (Splitters[1], 0)],
        [(Snp[10], 1), (Splitters[1], 1)],
        [(Snp[11], 0), (Splitters[1], 2)],
        [(Snp[25], 1), (Snp[26], 0)],
        [(Snp[23], 0), (Snp[22], 1)],
        [(Snp[23], 1), (Splitter, 0)],
        [(Output1, 0), (Splitter, 1)],
        [(Snp[71], 1), (Splitter, 2)],
        [(Ind[0], 0), (Splitter, 3)],
        [(Snp[22], 0), (Snp[21], 1)],
        [(Snp[45], 1), (Snp[47], 0)],
        [(Snp[13], 1), (Snp[14], 0)],
        [(Snp[15], 1), (Snp[16], 0)],
        [(Snp[27], 1), (Snp[28], 0)],
        [(Snp[32], 0), (Splitters[2], 0)],
        [(Snp[47], 1), (Splitters[2], 1)],
        [(Snp[46], 1), (Splitters[2], 2)],
        [(Snp[35], 1), (Snp[36], 0)],
        [(Snp[28], 1), (Splitters[3], 0)],
        [(Snp[46], 0), (Splitters[3], 1)],
        [(Snp[31], 1), (Splitters[3], 2)],
        [(Snp[16], 1), (Snp[17], 0)],
        [(Snp[14], 1), (Splitters[4], 0)],
        [(Snp[17], 1), (Splitters[4], 1)],
        [(Snp[18], 0), (Splitters[4], 2)],
        [(Snp[71], 0), (Snp[70], 1)],
        [(Snp[21], 0), (Splitters[5], 0)],
        [(Snp[20], 1), (Splitters[5], 1)],
        [(Snp[26], 1), (Splitters[5], 2)],
        [(Snp[70], 0), (Snp[38], 1)],
        [(Snp[1], 1), (Snp[8], 0)],
        [(Snp[8], 1), (Snp[9], 0)],
        [(Snp[10], 0), (Snp[9], 1)],
        [(Snp[19], 0), (Snp[18], 1)],
    ]

    return connections


def test_reduce_IV(connections):
    """
    Test block method and speed comparison with Index method.
    """
    # Index method, that is calculate the whole external S matrix, and index the ports
    index_start = time()
    circuit = rf.Circuit(connections, auto_reduce=True)
    nports = len(circuit.port_indexes)

    index_rst = circuit.s_external

    # Power/Phase Sweep Calculation
    for _ in range(30):
        power = np.random.rand(nports)
        phase = np.random.rand(nports)
        circuit.currents(power, phase)
        circuit.voltages(power, phase)

    index_end = time()

    return ((index_end - index_start) * 1000.0,)


if __name__ == "__main__":
    freq_n = 1001
    fcalls = 100
    std_rst = None
    connections = complex_cnxs(freq_n)
    rst = np.array([test_reduce_IV(connections) for _ in range(fcalls)])
    print(
        f"Total time in complex example: {np.mean(rst[:,0]):.4f} ms, min: {np.min(rst[:,0]):.4f} ms, std: {np.std(rst[:,0]):.4f} ms"
    )
```
The output is as follows,
```bash
(skrf) ➜  scikit-rf git:(master) ✗ python performance_test.py
Total time in complex example: 109.5408 ms, min: 102.6366 ms, std: 6.5582 ms
(skrf) ➜  scikit-rf git:(master) ✗ git switch CircuitCached
(skrf) ➜  scikit-rf git:(CircuitCached) ✗ python performance_test.py
Total time in complex example: 36.0482 ms, min: 33.7553 ms, std: 4.4588 ms
```

**Review by jhillairet — APPROVED** [review]
Nice! Glad to have discovered `cached_property` from [functools](https://docs.python.org/3/library/functools.html)!

**Comment by Asachoo** [comment]
The cache for commonly used properties in `Circuit` objects proves to be incredibly handy.

**Comment by jhillairet** [comment]
Ok for merging?

**Comment by Asachoo** [comment]
Yes, I consider it finished.

**Pull request merged**
