### PR TITLE
add format support to write_touchstone

### PR DESCRIPTION
**Pull request by aerialist**

### CODE REVIEW

**Comment by arsenovic** [comment]
this is great!  long been on the todo list. the travis is failing just for the python 3.3 which is due to some other problems i havent had time to dig into yet. 

thanks!

**Comment by aerialist** [comment]
Hi Alex,

This PR doesn't seem to be merged. Could you?

**Comment by arsenovic** [comment]
sorrty this is taking so long, i just need to go back and figure out where the change was made, because i think i made the same fix at some point.

**Comment by aerialist** [comment]
I saw you implemented it in networkset_2_spreadsheet function in io.general.py
And I tried to follow its argument names.

**Pull request merged**
