### PR TITLE
Correct error when asking db/ma from ri file

### PR DESCRIPTION
**Pull request by edumur**

### CODE REVIEW

**Comment by jhillairet** [comment]
wow, nice catch. Seems like a few users use the `ri` format! It also means this is not correctly tested.

**Comment by edumur** [comment]
To be fare, it was caught by one of the lab student.
We were both impressed that no one saw it before (we checked and the code had been written 11 years ago).

**Comment by jhillairet** [comment]
Could you add a test in `test_touchstone.py` and a simple touchstone file in that format?

**Comment by edumur** [comment]
I quickly added something that I hope is enough (no idea how these tests work).

If it is not enough, I will be back the 3rd of January ;) .

Live long and prosper 🖖.

**Comment by jhillairet** [comment]
> I quickly added something that I hope is enough (no idea how these tests work).

Great, many thanks!

 > Live long and prosper vulcan_salute.

Have nice holidays!

**Comment by jhillairet** [comment]
and thanks to lab student!

**Pull request merged**
