### PR TITLE
 Remove the Port Number Limitation for Circuit Current/Voltage Calculations

### PR DESCRIPTION
**Pull request by Asachoo**
## Description

While the current calculations for Circuit's `currents()` and `voltages()` are sufficiently accurate and practical, the necessity of adding a `splitter` has introduced some complications.

Firstly, the additional `splitter` slows down the computation. Secondly, it requires the reconstruction of some existing `Circuit` objects that previously did not use a `splitter` for parallel connections between Networks in a Node.

In this PR, I address these issues by computing the equivalent load impedance of the rest of the parallel Networks in the Node. This allows us to determine the actual transmission coefficients (Tau) of each Network in the Node. By doing this, we can bypass the introduction of `splitters` and directly compute the `Current` and `Voltage` of each Network within the Node.

The following example, although simple, effectively illustrates this change:

```python3
# Original connections using a splitter (tee)
cnx_with_tee = [
    [(port1, 0), (line1, 0)],
    [(line1, 1), (tee, 0)],
    [(line2, 0), (tee, 1)],
    [(line3, 0), (tee, 2)],
    [(line2, 1), (port2, 0)],
    [(line3, 1), (resistor, 0)],
]

# New connections without a splitter
cnx = [
    [(port1, 0), (line1, 0)],
    [(line1, 1), (line2, 0), (line3, 0)],
    [(line2, 1), (port2, 0)],
    [(line3, 1), (resistor, 0)],
]
```

This approach not only enhances computational efficiency but also maintains compatibility with existing `Circuit` objects that do not utilize `splitters` for parallel Networks Node in connections.

### CODE REVIEW

**Comment by Asachoo** [comment]
I used `ADS` to analyze a simple yet typical circuit and compared the current and voltage results with those obtained from `scikit-rf`.
### ADS Simulation Results
img_v3_02df_2b18328d-11f8-47fd-94b9-d539832a64eg

img_v3_02df_001b7f20-b315-4aa6-8e96-cdd5adc6d7bg

### scikit-rf Code and Output
`scikit-rf` code:
```python3
import skrf as rf

# Create Media object
freq = rf.Frequency(1, 10, 10, "ghz")
media = rf.media.DefinedGammaZ0(frequency=freq)

# Create Networks
res = media.resistor(R=50, name="res")
cap = media.capacitor(C=1e-12, name="cap")
ind = media.inductor(L=1e-9, name="ind")
tee = media.tee(name="tee")

# Create Circuit
gnd = rf.Circuit.Ground(frequency=freq, name="gnd")
port1 = rf.Circuit.Port(frequency=freq, name="port1")
port2 = rf.Circuit.Port(frequency=freq, name="port2")

connections = [
    [(port1, 0), (res, 0)],
    [(res, 1), (cap, 0), (ind, 0)],
    [(cap, 1), (port2, 0)],
    [(ind, 1), (gnd, 0)],
]

circuit = rf.Circuit(connections)

rst_v = circuit.voltages((1, 0), (0, 0))
rst_i = circuit.currents((1, 0), (0, 0))

for f, v_s in zip(freq, rst_v):
    print(f"{f}: {v_s[1]:.8f} V, {v_s[2]:.8f} V, {v_s[5]:.8f} V")
print()
for f, i_s in zip(freq, rst_i):
    print(f"{f}: {i_s[2]:.8f} A, {i_s[3]:.8f} A, {i_s[4]:.8f} A")

```
Output log:
```bash
(skrf) (base) ➜  scikit-rf git:(CircuitVoltages) ✗ python voltage_example.py 
1.0-1.0 GHz, 1 pts: 10.04981291+0.64790702j V, 0.09962581+1.29581405j V, -0.36157345+0.14489002j V
2.0-2.0 GHz, 1 pts: 10.29972401+1.35055779j V, 0.59944802+2.70111558j V, -1.04712142+1.03457009j V
3.0-3.0 GHz, 1 pts: 10.86968839+1.92993870j V, 1.73937678+3.85987739j V, -1.10833116+2.68390150j V
4.0-4.0 GHz, 1 pts: 11.59179430+2.14983263j V, 3.18358861+4.29966525j V, -0.14570654+4.18371567j V
5.0-5.0 GHz, 1 pts: 12.19157069+2.05940265j V, 4.38314137+4.11880529j V, 1.25314710+4.91658351j V
6.0-6.0 GHz, 1 pts: 12.59013806+1.84553748j V, 5.18027612+3.69107495j V, 2.51442174+5.02501712j V
7.0-7.0 GHz, 1 pts: 12.83544887+1.62191852j V, 5.67089774+3.24383704j V, 3.47688899+4.82487724j V
8.0-8.0 GHz, 1 pts: 12.98617003+1.42639103j V, 5.97234006+2.85278205j V, 4.17611519+4.51440549j V
9.0-9.0 GHz, 1 pts: 13.08142357+1.26432124j V, 6.16284715+2.52864248j V, 4.68276559+4.18483202j V
10.0-10.0 GHz, 1 pts: 13.14389689+1.13151063j V, 6.28779377+2.26302125j V, 5.05524802+3.87215667j V

1.0-1.0 GHz, 1 pts: -0.19900374+0.01295814j A, -0.00723147+0.00289780j A, 0.20623521-0.01585594j A
2.0-2.0 GHz, 1 pts: -0.19400552+0.02701116j A, -0.02094243+0.02069140j A, 0.21494795-0.04770256j A
3.0-3.0 GHz, 1 pts: -0.18260623+0.03859877j A, -0.02216662+0.05367803j A, 0.20477286-0.09227680j A
4.0-4.0 GHz, 1 pts: -0.16816411+0.04299665j A, -0.00291413+0.08367431j A, 0.17107824-0.12667097j A
5.0-5.0 GHz, 1 pts: -0.15616859+0.04118805j A, 0.02506294+0.09833167j A, 0.13110564-0.13951972j A
6.0-6.0 GHz, 1 pts: -0.14819724+0.03691075j A, 0.05028843+0.10050034j A, 0.09790880-0.13741109j A
7.0-7.0 GHz, 1 pts: -0.14329102+0.03243837j A, 0.06953778+0.09649754j A, 0.07375324-0.12893592j A
8.0-8.0 GHz, 1 pts: -0.14027660+0.02852782j A, 0.08352230+0.09028811j A, 0.05675430-0.11881593j A
9.0-9.0 GHz, 1 pts: -0.13837153+0.02528642j A, 0.09365531+0.08369664j A, 0.04471622-0.10898307j A
10.0-10.0 GHz, 1 pts: -0.13712206+0.02263021j A, 0.10110496+0.07744313j A, 0.03601710-0.10007335j A
```
### Conclusion
The comparison shows that both tools produce identical results.

**Comment by jhillairet** [comment]
It's  a great improvement, thank you! The [associated tutorial](https://scikit-rf.readthedocs.io/en/latest/examples/circuit/Voltages%20and%20Currents%20in%20Circuits.html) could mention this (and the way currents&voltages are calculated with this PR)

**Comment by Asachoo** [comment]
Maybe updating the example at [Wilkinson Power Splitter](https://scikit-rf.readthedocs.io/en/latest/examples/circuit/Wilkinson%20Power%20Splitter.html) would be more beneficial.

The original `Wilkinson Power Divider example` specifically addressed how to calculate voltages and currents in `Circuits` with parallel components by introducing the "T" `Network`.

This updated notebook demonstrates scikit-rf’s capability to directly calculate voltages and currents in complex `Circuits` and highlights the advantages of the 'Circuit' method over the 'classic' approach for handling complex `Circuit`.

**Comment by jhillairet** [comment]
> Maybe updating the example at [Wilkinson Power Splitter](https://scikit-rf.readthedocs.io/en/latest/examples/circuit/Wilkinson%20Power%20Splitter.html) would be more beneficial.
> 
> The original `Wilkinson Power Divider example` specifically addressed how to calculate voltages and currents in `Circuits` with parallel components by introducing the "T" `Network`.

Yes, you're right !

**Comment by Asachoo** [comment]
> Great addition! Still, I think your approach, which I find quite original, could be explained in the current/voltage notebook example. What do you think?

Thank you for your recognition! Absolutely, I'll add a new section to the current/voltage notebook example to introduce the enhanced method for calculating currents and voltages introduced in this PR.

**Comment by Asachoo** [comment]
@jhillairet I have edited this notebook draft to explain the modifications I made to the voltage and current methods in this PR.

Since I am more familiar with coding and numerical operations than with the conceptual nuances of microwave networks, there may be some inappropriate terminology in this tutorial. I would greatly appreciate any feedback or suggestions for improving this notebook.

**Review by jhillairet — APPROVED** [review]

**Comment by jhillairet** [comment]
another great PR, thank you @Asachoo !

**Pull request merged**
