### PR TITLE
Fix inductor units in media docstrings

### PR DESCRIPTION
**Pull request by ericwrice**

### CODE REVIEW

**Comment by Vinc0110** [comment]
Good catch, inductance should not be in Farad.
Personally, I would prefer the singular form for the unit, i.e. "Henry".

**Comment by ericwrice** [comment]
I can certainly change it to singular if that is preferred, I went with plural to be consistent with the resistor and capacitor doc strings.

**Comment by Vinc0110** [comment]
It's probably not that important. Keeping it consistent is also a good thing.

Just for future reference, there exists a NIST guide with rules for spelling SI units:
https://www.nist.gov/pml/special-publication-811/nist-guide-si-chapter-9-rules-and-style-conventions-spelling-unit-names

Following those rules would certainly require a major revision on many docstrings...

**Review by jhillairet — APPROVED** [review]
Good catch, thank you !

**Pull request merged**
