### PR TITLE
Added group delay feature to networkPlotWidget.py

### PR DESCRIPTION
**Pull request by wbarnha**
I like data_grabber.py and I'd like to add some functionality to display group delay for s-parameters. This configuration only works for .s2p files, at the moment. Would there be any interest in this feature? The current implementation is pretty sloppy, but I can improve it, should there be interest.

### CODE REVIEW

**Comment by arsenovic** [comment]
hey why did you close this?   i think it would be a good addition

**Comment by wbarnha** [comment]
Sorry about that. I felt the code was a bit sloppy and I wanted to work on it a little more before it got some attention. If you believe this is a good addition, you're welcome to use it!

**Comment by wbarnha** [comment]
Undid a bit of hard-coding in case there are functions in the future with similar issues as group_delay.

**Comment by arsenovic** [comment]
is this ready to merge or work in progress?

**Comment by wbarnha** [comment]
You can go ahead and merge it now.

**Pull request merged**
