### PR TITLE
Fix IEEEP370 deembedding methods for dataset with existing dc point or interpolation required

### PR DESCRIPTION
**Pull request by mhuser**
Fix issues with IEEEP370 deembedding methods when there is a DC point and add test cases for the issue not to come back again.

### CODE REVIEW

**Comment by mhuser** [comment]
Bonus: implement interpolation when the 2x-Thru and FIX-DUT-FIX have not an harmonic sweep frequency vector (a vector were each frequency is a multiple of f[0]).

It is better to measure with the harmonic sweep, but in case were the frequency is close to that (e.g. quasi-integer multiple of f[0], interpolation can be convenient and it is proposed by the IEEEP370 matlab implementation.

**Comment by mhuser** [comment]
I will need the help of a courageous developer to double-check this! 😄 
@jhillairet can we add this to the forecoming fixes release ?

**Comment by mhuser** [comment]
@jhillairet shall we wait for the release of #733 before merging this (still on hold for approbation)?

**Comment by jhillairet** [comment]
Sure, ok.

**Comment by jhillairet** [comment]
I think we can merge

**Comment by mhuser** [comment]
Thanks!

**Pull request merged**
