### PR TITLE
Do not generate subnetworks all the time but provide them dynamically

### PR DESCRIPTION
**Pull request by FranzForstmayr**
Do not generate subnetworks all the time but provide them dynamically if requested.

This is an alternative approach for #807, open for discussion

### CODE REVIEW

**Comment by FranzForstmayr** [comment]
Subnetworks aren't shown in docs anymore...

**Comment by jhillairet** [comment]
> Subnetworks aren't shown in docs anymore...

and I guess neither in the autocompletion, isn't?

**Comment by FranzForstmayr** [comment]
I don't think so. I work with vscode, which hadn't autocompletion for this dynamically generated properties anyway.

**Comment by FranzForstmayr** [comment]
I did some research about dynamic properties and autocompletion today.

It's not possible to get static typing or type hints (as for mypy or any other typechecker) with dynamically created properties, as the type checker does not execute the code even once, that's why it's not aware of the dynamic attributes.

Interactive Sessions like jupyter or ipython have a concept which is called autosuggestion which can handle dynamic properties. The list of available properties is taken from the __dir__() method.

So this PR removes dynamic property setting and generates all available dynamic attributes on the fly, as the __getattr__() method is overloaded. Autosuggestion for interactive Sessions and Jupyter is done via the __dir__ method.

Open for Feedback :)

If this works well, this method could be expanded to replace the code, which creates the plotting methods for a Network or NetworkSet

**Comment by FranzForstmayr** [comment]
Still have to investigate sphinx build

**Comment by jhillairet** [comment]
what about what has been proposed in #828 concerning secondary properties?

**Comment by FranzForstmayr** [comment]
The secondary property generation is error prone in general and wouldn't be needed anymore.

**Comment by FranzForstmayr** [comment]
I think we can start review at this point, although I think we should not merge before 0.25 release. A follow up PR #848 will unify the plot code generation.

**Review by jhillairet — APPROVED** [review]
very nice addition, hats off!

**Comment by FranzForstmayr** [comment]
I think this one is fine. #848 already includes this PR, but isn't finished yet.

**Review by jhillairet — APPROVED** [review]

**Pull request merged**
