### PR TITLE
A generalized/abstract Network connection method

### PR DESCRIPTION
**Pull request by Asachoo**
## Summary
Inspired by the `Circuit class`, I've adapted the `Hallbjörner's circuit algorithm` to the `Network class`. This adaptation combines the **simplicity and efficiency** of the `Network` approach with the **flexible connectivity** of the `Circuit` method.

The method reflects familiar from `Circuit.s`, `Circuit._Xk`, and `Circuit.X`. However, adjustments have been made to the `C` matrix assignment due to the **single concatenated intersection** and the absence of the `Port` concept.

I'm currently calling this method `parallelconnect`. As English is not my first language, I'm open to suggestions for a more fitting name.

Below are some examples showcasing the versatility of the `parallelconnect` method:

### Setup
```python3
Python 3.9.19 (main, May  6 2024, 19:43:03) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import skrf as rf
>>>
>>> def gen_s(f_num = 101, p_num= 2):
...     real_part = np.random.rand(f_num, p_num, p_num) * 2 - 1
...     imag_part = np.random.rand(f_num, p_num, p_num) * 2 - 1
...     return real_part + 1j * imag_part
... 
>>> 
>>> # Fix the random seed for reproducibility
>>> np.random.seed(123)
>>> 
>>> # Create a frequency object and media
>>> freq = rf.Frequency(1, 100, 101, 'ghz')
>>> media = rf.media.DefinedGammaZ0(frequency=freq, z0=50)
>>> 
>>> port1 = rf.Circuit.Port(frequency=freq, name='port1', z0=50)
>>> port2 = rf.Circuit.Port(frequency=freq, name='port2', z0=50)
>>> port3 = rf.Circuit.Port(frequency=freq, name='port3', z0=50)
>>> port4 = rf.Circuit.Port(frequency=freq, name='port4', z0=50)
>>> 
>>> # Create functional components
>>> tee = media.tee(name='tee')
>>> open_p = media.open(name='open_p')
>>> 
>>> # Create 3 networks
>>> ntwka = rf.Network(frequency=freq, s=gen_s(p_num=2), name='ntwka', z0=25)
>>> ntwkb = rf.Network(frequency=freq, s=gen_s(p_num=2), name='ntwkb', z0=75)
>>> ntwkc = rf.Network(frequency=freq, s=gen_s(p_num=4), name='ntwkc', z0=[50, 60, 70, 80])
>>> 
```

### Example 1: Open a Network's port
```python3
>>> # Traditional way
>>> ntwk_trad = rf.connect(ntwkc, 3, open_p, 0)
>>> 
>>> # This method
>>> ntwk_par = rf.parallelconnect(ntwkc, [3])
>>> 
>>> # Check if they are the same
>>> np.allclose(ntwk_trad.s, ntwk_par.s)
True
```

### Example 2: Normal Connect
```python3
>>> # Traditional way
>>> ntwk_trad = rf.connect(ntwka, 0, ntwkb, 1)
>>> 
>>> # This method
>>> ntwk_par = rf.parallelconnect([ntwka, ntwkb], [0, 1])
>>> 
>>> # Check if they are the same
>>> np.allclose(ntwk_trad.s, ntwk_par.s)
True
```

#### A Simple example
```python3
>>> # Traditional way
>>> ntwk_trad = rf.innerconnect(ntwkc, 0, 1)
>>> 
>>> # This method
>>> ntwk_par = rf.parallelconnect(ntwkc, [[0, 1]])
>>> 
>>> # Check if they are the same
>>> np.allclose(ntwk_trad.s, ntwk_par.s)
True
```
#### A more complex example
```python3
>>> # Traditional way
>>> ntwk_trad = rf.connect(ntwkc, 2, tee, 0)
>>> ntwk_trad = rf.innerconnect(ntwk_trad, 1, 3)
>>> ntwk_trad = rf.innerconnect(ntwk_trad, 1, 2)
>>>
>>> # Circuit way
>>> cnx = [
...     [(port1, 0), (ntwkc, 0)],
...     [(ntwkc, 1), (ntwkc, 2), (ntwkc, 3)]
... ]
>>> ntwk_ckt = rf.Circuit(cnx).network
>>> 
>>> # This method
>>> ntwk_par = rf.parallelconnect(ntwkc, [[1, 2, 3]])
>>> 
>>> # Check if they are the same
>>> np.allclose(ntwk_trad.s, ntwk_par.s)
True
>>> np.allclose(ntwk_ckt.s, ntwk_par.s)
True
```

### Example 4: Tee connect
```python3
>>> # Traditional way
>>> ntwk_trad = tee.copy()
>>> ntwk_trad = rf.connect(ntwk_trad, 0, ntwka, 1)
>>> ntwk_trad = rf.connect(ntwk_trad, 1, ntwkb, 0)
>>> ntwk_trad = rf.connect(ntwk_trad, 2, open_p, 0)
>>> ntwk_trad
2-Port Network: 'tee',  1.0-100.0 GHz, 101 pts, z0=[25.+0.j 75.+0.j]
>>> 
>>> # Circuit way
>>> cnx = [
...     [(port1, 0), (ntwka, 0)],
...     [(port2, 0), (ntwkb, 1)],
...     [(ntwka, 1), (ntwkb, 0), (open_p, 0)]
... ]
>>> ntwk_ckt = rf.Circuit(cnx).network
>>> ntwk_ckt
2-Port Network: '',  1.0-100.0 GHz, 101 pts, z0=[50.+0.j 50.+0.j]
>>> ntwk_ckt.renormalize(z_new=ntwk_trad.z0)
>>> 
>>> # This method
>>> ntwk_par = rf.parallelconnect([ntwka, ntwkb, open_p], [1, 0, 0])
>>> ntwk_par
2-Port Network: '',  1.0-100.0 GHz, 101 pts, z0=[25.+0.j 75.+0.j]
>>> 
>>> # Check if they are the same
>>> np.allclose(ntwk_trad.s, ntwk_par.s)
True
>>> np.allclose(ntwk_ckt.s, ntwk_par.s)
True
>>> 
```

### Example 5: Parallel Connect
```python3
>>> # Circuit way
>>> cnx = [
...     [(port1, 0), (ntwka, 0)],
...     [(port2, 0), (ntwkb, 0)],
...     [(port3, 0), (ntwkc, 2)],
...     [(port4, 0), (ntwkc, 3)],
...     [(ntwka, 1), (ntwkb, 1), (ntwkc, 0), (ntwkc, 1)]
... ]
>>> ntwk_ckt = rf.Circuit(cnx).network
>>> ntwk_ckt
4-Port Network: '',  1.0-100.0 GHz, 101 pts, z0=[50.+0.j 50.+0.j 50.+0.j 50.+0.j]
>>> 
>>> # This method
>>> ntwk_par = rf.parallelconnect([ntwka, ntwkb, ntwkc], [1, 1, [0, 1]])
>>> ntwk_par
4-Port Network: '',  1.0-100.0 GHz, 101 pts, z0=[25.+0.j 75.+0.j 70.+0.j 80.+0.j]
>>> 
>>> # Renormalize the ports
>>> ntwk_par.renormalize(z_new=ntwk_ckt.z0)
>>> 
>>> # Check if they are the same
>>> np.allclose(ntwk_ckt.s, ntwk_par.s)
True
```

I'm confident that `parallelconnect` can enable even more sophisticated `Network` configurations and look forward to exploring its full potential with your feedback and suggestions.

### CODE REVIEW

**Comment by jhillairet** [comment]
It's an interesting approach, thank you @Asachoo!

It allows connecting complex circuit with a minimum number of lines of code, but at a price of loss of explicit code (less intuitive?). Let's discuss with others' feelings.

**Comment by Asachoo** [comment]
I appreciate the feedback and understand the point you're making, apologies if my demonstration of the method's flexibility obscured its core essence @jhillairet .

To clarify, the method essentially allows for the connection of one or more ports of one or more Networks using a splitter, which can simplify the coding process by reducing the number of lines needed. In the example I showed, **only one of the lists** in the circuit pathway carries significance (as it represents the actual connection), while the other lists are connected to the Port.

Given the diversity of connections that this implicit splitter port can handle (for instance, 1. multiple ports of a single Network, equivalent to `innerconnect()`; 2. one port from two different Networks, equivalent to `connect()`; 3. one port from multiple Networks, equivalent to `tee()`/`splitter()`; and 4. multiple ports from multiple Networks, equivalent to a simple `Circuit`). It could be concluded that the parameters should be the sequence of Networks and their respective `Ports` that are connected to this implicit splitter.

The scenario for this method is to provide a convenient **shortcut** for connecting multiple Networks together, which overlaps significantly with `splitter()`, without the need to guess which ports change after each `connect()` as shown in examples. Moreover, because the `splitter` is implicitly introduced, it results in less computational overhead compared to explicit `splitter()` connect or `Port` inclusion in the `Circuit` method.

I hope I've clarified the principles and scenarios for this method, and welcome any feedback and suggestions from everyone.

**Review by jhillairet — APPROVED** [review]
I'm OK with this additional way of connecting Networks together. Just fearing that adding a new way of connecting Networks could eventually obscurate (new) users. @Asachoo ,  could you plan to make some associated notebook documentation?

@FranzForstmayr @mhuser @Vinc0110 @Ttl @arsenovic @dvincentwest, do you have any advice?

**Comment by Asachoo** [comment]
Thanks for your valuable feedback and interest in this new approach @jhillairet @FranzForstmayr.
I'll updating the [Connecting Networks tutorial](https://scikit-rf.readthedocs.io/en/latest/tutorials/Connecting_Networks.html) to include the application and comparison of this method shortly.

**Review by jhillairet — APPROVED** [review]

**Comment by jhillairet** [comment]
@Asachoo do you plan to add the tutorial to this PR or should I merge it?

**Comment by Asachoo** [comment]
> @Asachoo do you plan to add the tutorial to this PR or should I merge it?

Sorry for the delay in updating this tutorial @jhillairet.

I’ve added three new examples and a summary comparing `parallelconnect()` with other methods to the `Connecting Networks tutorial`. I’d love to hear any suggestions or feedback!

I believe that, in the absence of further suggestions, this PR is ready to be merged.

**Review by jhillairet — APPROVED** [review]

**Pull request merged**
