### PR TITLE
Update & Streamline requirements

### LINKED ISSUE #493: ModuleNotFoundError for dependency networkx in rf.Circuit.plot_graph()
Calling the plot_graph method of rf.Circuit without networkx installed gives an ImportError/ModuleNotFoundError rather than failing gracefully. See code below, based on an example from the documentation.

```python
def mBVD_model(freq:rf.Frequency, cs, ls, rs, cp, rp, rc):
    tl_media = rf.DefinedGammaZ0(freq, z0=50, gamma=1j * freq.w / rf.c)
    Cs = tl_media.capacitor(cs, name='Cs')
    Ls= tl_media.inductor(ls, name='Ls')
    Rs = tl_media.resistor(rs, name='Rs')
    Cp = tl_media.capacitor(cp, name='Cp')
    Rp = tl_media.resistor(rp, name='Rp')
    Rc = tl_media.resistor(rc, name='Rc')

    gnd = rf.Circuit.Ground(freq, name='gnd')
    port1 = rf.Circuit.Port(freq, name='port1', z0=50)

    cnx = [
        [(gnd, 0), (port1, 0), (port1, 1), (Rc, 1), (Rc, 2),
         (Cp, 2), (Cp, 3), (Rp, 3), (Rp, 0),
         (Cs, 2), (Cs, 4), (Ls, 4), (Ls, 5), (Rs, 5), (Rs, 0)],
    ]
    cir = rf.Circuit(cnx)
    cir.plot_graph(network_labels=True, network_fontsize=15,
                   port_labels=True, port_fontsize=15,
                   edge_labels=True, edge_fontsize=10)
    ntw = cir.network
    return ntw
```

```python
Traceback (most recent call last):
  File "C:\Users\ander906\PycharmProjects\scratch_work\venv\lib\site-packages\skrf\circuit.py", line 359, in graph
    import networkx as nx
  File "C:\Program Files\JetBrains\PyCharm 2021.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'networkx'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\ander906\PycharmProjects\scratch_work\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-a01675e7785b>", line 1, in <module>
    n2 = mBVD_model(n.frequency, 1E-15, 206E-9, 12.38, 100E-15, 31, 0.1)
  File "<ipython-input-4-2c16593186ca>", line 106, in mBVD_model
    edge_labels=True, edge_fontsize=10)
  File "C:\Users\ander906\PycharmProjects\scratch_work\venv\lib\site-packages\skrf\plotting.py", line 2072, in plot_circuit_graph
    G = self.G
  File "C:\Users\ander906\PycharmProjects\scratch_work\venv\lib\site-packages\skrf\circuit.py", line 345, in G
    return self.graph()
  File "C:\Users\ander906\PycharmProjects\scratch_work\venv\lib\site-packages\skrf\circuit.py", line 361, in graph
    raise ImportError('networkx package as not been installed and is required. ')
ImportError: networkx package as not been installed and is required. 
```

### PR DESCRIPTION
**Pull request by JAnderson419**
This is to update the setup.py (closes #493) and also makes an effort to move some of the development/build dependencies out of requirements.txt and into optional settings in setup.py. Github actions may need updating to grab the optional dependencies from setup.py for tests to run.

### CODE REVIEW

**Comment by JAnderson419** [comment]
I wasn't sure if the ipython stuff for ipywidgets should be a default dependency or not - I believe a large effort was made some years back to minimize the core required dependencies and instruct users to install optional dependencies as needed for features like GUI and instrument control.

**Comment by FranzForstmayr** [comment]
I think ipython and so GUI stuff should not be installed by default, because much smaller environments are possible. 

What about using poetry to manage dependencies?

**Comment by jhillairet** [comment]
Great, thank you. Is it ok to be merged? 

@FranzForstmayr how this would be improved using poetry (never used)?

**Comment by FranzForstmayr** [comment]
poetry simplifies dependency management, build and packing of python projects.
I'll have to check how poetry can fit into skrf and will make a PR later. :)

**Comment by jhillairet** [comment]
@JAnderson419 is ok to be merged?

**Comment by JAnderson419** [comment]
I think it is okay from my end. It looks like there is a separate yml file for the qt app requirements, although many of the build requirements point towards 3.5 and should probably be updated in the future.

**Comment by jhillairet** [comment]
Thank you !

**Comment by JAnderson419** [comment]
This PR broke the interactive docs (they display fail to execute as I didn't have it installing skrf itself). I am working on fixing the yml and will submit another pull request once I confirm its fixed.

**Pull request merged**
