### PR TITLE
Code style, Pep8, whitespace, and some minor fixes

### PR DESCRIPTION
**Pull request by TheWylieStCoyote**
I have made some changes to make the code more PEP8 friendly. I made no real changes to the functionality of the code except for some try except statements for file handling with "with" statements. I did fixed a lot of trailing white spaces and extra lines.

Its still not perfect, but this should be a good step.

### CODE REVIEW

**Comment by TheWylieStCoyote** [comment]
Sorry forgot to run the tests,
Downside of working on something when one has the flu.

I will try and fix this up and resubmit it.

**Comment by arsenovic** [comment]
@TheWylieStCoyote 
it seems like there are just a couple errors in this commit, appearing in the calibration module.  looks like you appended an `i` to 
the polynomial `r` property access

 ```File "/home/travis/build/scikit-rf/scikit-rf/skrf/calibration/calibration.py", line 1275, in run
    b1[k], b2[k] = p.ri
```

and some other similar typo. do you know how these happened? 


overall these changes are positive, and i would like to commit them once fixed. however, because our coverage is not great i am in general  scared of broad changes. in the future you may consider  making separate commits, and perhaps even seperate PR's for coding semantics and functionality changes.

**Comment by TheWylieStCoyote** [comment]
I was using vim, I think thats your answer for why there was a "i". 

Other ones I am not sure of, I did it all manually. I do not really trust automatic code tools for somethings. I have been burned bad in the past. I had the week off from work because I had the flu, so what better thing can I do then pick a project and work on it.

I will post soon a PR that is just removal of just trailing whitespaces and changing tabs to 4 spaces. I have a couple of code changes I would like to make. Nothing that a user of this project would see, just some handling of files and stuff like that. The big stuff is a little down that road.

What is not covered under unit tests right now? 
I will try and fix that also in future commits.

**Comment by arsenovic** [comment]
ok this sounds great.   the test coverage can be seen by using the **coveralls** service. if you look at the scikit-rf readme on github, you will see a badge that states the coverage. if you click this badge you go to 
https://coveralls.io/r/scikit-rf/scikit-rf

which breaks down coverage file-by-file, and lets you know if you are increasing or decreasing.

**Pull request closed without merging**
