### PR TITLE
Add Circuit.update_networks() to API page.

### PR DESCRIPTION
**Pull request by Asachoo**
Added Circuit.update_networks() method description to API page.

Sorry for ignoring the API page check when introducing the method.

### CODE REVIEW

**Review by jhillairet — APPROVED** [review]
I'll make a minor release eventually to include this

**Comment by Asachoo** [comment]
> I'll make a minor release eventually to include this

Thanks!

**Comment by FranzForstmayr** [comment]
> I'll make a minor release eventually to include this

It would be enough to trigger the readthedocs build from master if this is possible.

**Comment by jhillairet** [comment]
> > I'll make a minor release eventually to include this
> 
> It would be enough to trigger the readthedocs build from master if this is possible.

sure, you're right. I was also hoping for #1081 to be completed

**Pull request merged**
