### PR TITLE
TDR example based on measurements

### PR DESCRIPTION
**Pull request by mhuser**
Some new artefacts where manufactured in an attempt to provide a measurement-based time domain reflectometry example.

### CODE REVIEW

**Comment by mhuser** [comment]
I shall come back soon with VNA measurements and an ipython notebook.

**Comment by arsenovic** [comment]
ok i will wait to merge then.

**Comment by mhuser** [comment]
Hi, unfortunately not yet, but I will try to put the finishing touch this weekend!

**Comment by mhuser** [comment]
This is done, but unfortunately it became almost a monster and possibly missed its initial target.

**Pull request merged**
