### PR TITLE
preliminary noise deembedding

### PR DESCRIPTION
**Pull request by FournierVincent**
1. changed network.py to introduce a deembedding noise capability
- noise de_embedding according to the formula : CA2 = inv(A1) (CB - CA) inv(A1)t
2. separated the set_noise_a() from read_touchtone()
3. added tests/test_noise_deembed.py
- basic check : compare deembedded network to the original network when an access network is cascaded
4. setter for noise_parameters
I tried to define a N.noise_par property, consisting of the sub parameters (nfmin_db,g_opt, rn) and define the N.noise from the set_noise_a()
... and failed. This looks too difficult for a new comer in object oriented programming, old, tired, ill, with little time availability in the coming days/weeks ... 
... Yes, please help

Should I create a draft pull request or a pull request ?

### CODE REVIEW

**Comment by TomWoo** [comment]
> 1. changed network.py to introduce a deembedding noise capability
> 
> * noise de_embedding according to the formula : CA2 = inv(A1) (CB - CA) inv(A1)t
> 
> 1. separated the set_noise_a() from read_touchtone()
> 2. added tests/test_noise_deembed.py
> 
> * basic check : compare deembedded network to the original network when an access network is cascaded
> 
> 1. setter for noise_parameters
>    I tried to define a N.noise_par property, consisting of the sub parameters (nfmin_db,g_opt, rn) and define the N.noise from the set_noise_a()
>    ... and failed. This looks too difficult for a new comer in object oriented programming, old, tired, ill, with little time availability in the coming days/weeks ...
>    ... Yes, please help
> 
> Should I create a draft pull request or a pull request ?

Good start. There's some clean-up work to do...
No need to copy files out of the skrf folder to make changes. Git allows you to track edits and roll back if necessary. It would be good if you can make a clean pull request w/o duplicate files (to maintain revision history). Otherwise, you can send me the files with your changes and I'll make a PR for you. Also, feel free to delete code under 'if False...' because it's easy to see what you replace using GutHub's diff tools.
I still think that section of code under connect() should be moved elsewhere. I just noticed that a de_embed() method already exists, so why not put it there? I'll leave it up to you (and others), but adding a deembed boolean for use under connect seems a little confusing.
Stepping through the noise deembedding test, I found that the 'deembed' network is noiseless, which makes the test pointless. See if you can demonstrate a passing test w/ a noisy fixture. Otherwise, the test just runs though loss-based deembedding, which we already know works.
As for item 4, what's the motivation for defining a single noise_par property? To group noise params? I suppose you could define a container class or use a dictionary, but why not keep it simple? If you're trying to define a correlation matrix property, then the 's' property can serve as a good reference.

**Comment by FournierVincent** [comment]
SOS ! Too many difficulties at a time. 
I can't load the project again. I have no idea how to deal with the development environment. 
There are conflicts between the directory structure imported by anaconda. I don't know how to tell spyder to use my version 0.15.2.me instead of scikit-rf 0.14.9. I am completely stuck. 

Please find the files attached and complete the upload for me. 
I will start learning things one at a time for future collaborations but I definitely need experienced people to take care this time. 
[network.py.txt](https://github.com/scikit-rf/scikit-rf/files/4402952/network.py.txt)
[thru.s2p.txt](https://github.com/scikit-rf/scikit-rf/files/4402959/thru.s2p.txt)
[test_noise_deembed.py.txt](https://github.com/scikit-rf/scikit-rf/files/4402962/test_noise_deembed.py.txt)
Thanck you !
Vincent

**Comment by jhillairet** [comment]
You have the possibility of using anaconda to define [environments](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html): you can use one for development and one for "production". 

Otherwise, a simple method can also to i) remove scikit from anaconda, and ii) only use the version pulled from your github. To do that in Spyder, you can define in `tools>PYTHONPATH manager` the path to your development version of scikit.

**Comment by FournierVincent** [comment]
I get into even more complicated troubles. I don't have the necessary background to perform so complicated tasks. 

remove "scikit-rf" from anaconda env "labview_py36"

1. use anaconda to specify an environment
I don't understand what I should do. I don't understand the concepts. 

2. spyder python_path set to (I tried both)

C:\Users\nxf59071\AppData\Roaming\Python\Python36\site-packages\scikit-rf\skrf
C:\Users\nxf59071\AppData\Roaming\Python\Python36\site-packages\scikit-rf\

Ipython doesn't initialize : 
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\Users\nxf59071\AppData\Roaming\Python\Python36\site‑packages\scikit‑rf\io\__init__.py", line 28, in 
File "C:\Users\nxf59071\AppData\Roaming\Python\Python36\site‑packages\scikit‑rf\io\general.py", line 33, in 
ModuleNotFoundError: No module named 'six'

**Comment by jhillairet** [comment]
There is a problem with the PR, all the files have been modified. We are working on it with @FournierVincent.

**Comment by TomWoo** [comment]
@FournierVincent
1. Following the docs jhillairet linked to, you can create a python environment specific to this project from the requirements.txt file and switch to it using the 'activate <env_name>' shell command w/o polluting your base python installation.
2. The error arises from the extraneous files in the io directory are masking python builtins. Ipython should work after you remove them. It would be really helpful if you can reintroduce your patches in a new fork w/o changing other files so that we can take a clean look at it. It would've also prevented this issue. Let's make sure the deembed test passes before further commits.

**Comment by jhillairet** [comment]
The correct PR is now #344 . I'm closing this one, but the discussion is kept of course.

**Pull request closed without merging**
