### PR TITLE
scaled frequency units

### PR DESCRIPTION
**Pull request by soxand16**
Resolves Issue #1099.

### CODE REVIEW

**Comment by jhillairet** [comment]
Is the reading of a file with corrected frequencies has the correct frequencies?

**Comment by soxand16** [comment]
@jhillairet Importing data from a csv saved using `network_2_spreadsheet` isn't part of my workflow, but I don't see any function designed to read in that particular csv format. 

There is `read_pna_csv` and functions like it that return a data frame and network, but they are specifically tailored for Agilient PNA output and do not work on a csv outputted by `network_2_spreadsheet` due to formatting differences.

**Comment by jhillairet** [comment]
OK. Just wondering the impact on other users. But indeed, the label of the frequency column was supposed to be scaled to the unit, so your PR is fully justified.

**Review by jhillairet — APPROVED** [review]

**Comment by jhillairet** [comment]
Thank you @soxand16

**Pull request merged**
